[#boost-asio-basic_socket-async_connect]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::async&lowbar;connect
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous connect&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConnectToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ConnectToken, void (boost&colon;&colon;system&colon;&colon;error&lowbar;code)&gt;(
        declval&lt;initiate&lowbar;async&lowbar;connect&gt;(), token,
        peer&lowbar;endpoint, declval&lt;boost&colon;&colon;system&colon;&colon;error&lowbar;code&amp;&gt;()))
async&lowbar;connect(
    xref:boost/asio/basic_socket/endpoint_type.adoc[endpoint&lowbar;type] const& peer&lowbar;endpoint,
    ConnectToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

== Description

This function is used to asynchronously connect a socket to the specified remote endpoint&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

The socket is automatically opened if it is not already open&period; If the connect fails, and the socket was automatically opened, the socket is not returned to the closed state&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error // Result of operation.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code) 
----
== Example
[,cpp]
----
void connect_handler(const boost::system::error_code& error)
{
  if (!error)
  {
    // Connect succeeded.
  }
}

...

boost::asio::ip::tcp::socket socket(my_context);
boost::asio::ip::tcp::endpoint endpoint(
    boost::asio::ip::address::from_string("1.2.3.4"), 12345);
socket.async_connect(endpoint, connect_handler);
----
== Per&hyphen;Operation Cancellation
On POSIX or Windows operating systems, this asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`
* `cancellation&lowbar;type&colon;&colon;total`

== Parameters

[cols=2]
|===
| Name
| Description
| *peer&lowbar;endpoint*
| The remote endpoint to which the socket will be connected&period; Copies will be made of the endpoint object as required&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the connect completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
