[#boost-asio-basic_socket-at_mark-0e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::at&lowbar;mark
:relfileprefix: ../../../
:mrdocs:

Determine whether the socket is at the out&hyphen;of&hyphen;band data mark&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

Determine whether the socket is at the out&hyphen;of&hyphen;band data mark&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/basic_socket/at_mark-09.adoc[at&lowbar;mark]() const;
----

[.small]#xref:boost/asio/basic_socket/at_mark-09.adoc[_» more&period;&period;&period;_]#

Determine whether the socket is at the out&hyphen;of&hyphen;band data mark&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/basic_socket/at_mark-02.adoc[at&lowbar;mark](boost::system::error&lowbar;code& ec) const;
----

[.small]#xref:boost/asio/basic_socket/at_mark-02.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

A bool indicating whether the socket is at the out&hyphen;of&hyphen;band data mark&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
