[#boost-asio-basic_socket-close-06]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::close
:relfileprefix: ../../../
:mrdocs:

Close the socket&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
close();
----

== Description

This function is used to close the socket&period; Any asynchronous send, receive or connect operations will be cancelled immediately, and will complete with the boost&colon;&colon;asio&colon;&colon;error&colon;&colon;operation&lowbar;aborted error&period;

[NOTE]
For portable behaviour with respect to graceful closure of a connected socket, call shutdown() before closing the socket&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period; Note that, even if the function indicates an error, the underlying descriptor is closed&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
