[#boost-asio-basic_socket-connect-00f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::connect
:relfileprefix: ../../../
:mrdocs:

Connect the socket to the specified endpoint&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
connect(xref:boost/asio/basic_socket/endpoint_type.adoc[endpoint&lowbar;type] const& peer&lowbar;endpoint);
----

== Description

This function is used to connect a socket to the specified remote endpoint&period; The function call will block until the connection is successfully made or an error occurs&period;

The socket is automatically opened if it is not already open&period; If the connect fails, and the socket was automatically opened, the socket is not returned to the closed state&period;

== Example
[,cpp]
----
boost::asio::ip::tcp::socket socket(my_context);
boost::asio::ip::tcp::endpoint endpoint(
    boost::asio::ip::address::from_string("1.2.3.4"), 12345);
socket.connect(endpoint);
----
== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *peer&lowbar;endpoint*
| The remote endpoint to which the socket will be connected&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
