[#boost-asio-basic_socket-non_blocking-0e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::non&lowbar;blocking
:relfileprefix: ../../../
:mrdocs:

Gets the non&hyphen;blocking mode of the socket&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
non&lowbar;blocking() const;
----

== Description

[NOTE]
The non&hyphen;blocking mode has no effect on the behaviour of asynchronous operations&period; Asynchronous operations will never fail with the error boost&colon;&colon;asio&colon;&colon;error&colon;&colon;would&lowbar;block&period;

== Return Value

`true` if the socket&apos;s synchronous operations will fail with boost&colon;&colon;asio&colon;&colon;error&colon;&colon;would&lowbar;block if they are unable to perform the requested operation immediately&period; If `false,` synchronous operations will block until complete&period;


[.small]#Created with https://www.mrdocs.com[MrDocs]#
