[#boost-asio-basic_socket-remote_endpoint-0c]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket.adoc[basic&lowbar;socket]::remote&lowbar;endpoint
:relfileprefix: ../../../
:mrdocs:

Get the remote endpoint of the socket&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&period;hpp&gt;`

Get the remote endpoint of the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket/endpoint_type.adoc[endpoint&lowbar;type]
xref:boost/asio/basic_socket/remote_endpoint-001.adoc[remote&lowbar;endpoint]() const;
----

[.small]#xref:boost/asio/basic_socket/remote_endpoint-001.adoc[_» more&period;&period;&period;_]#

Get the remote endpoint of the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket/endpoint_type.adoc[endpoint&lowbar;type]
xref:boost/asio/basic_socket/remote_endpoint-008.adoc[remote&lowbar;endpoint](boost::system::error&lowbar;code& ec) const;
----

[.small]#xref:boost/asio/basic_socket/remote_endpoint-008.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

* An object that represents the remote endpoint of the socket&period;
* An object that represents the remote endpoint of the socket&period; Returns a default&hyphen;constructed endpoint object if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
