[#boost-asio-basic_file-2constructor-0c5]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_file.adoc[basic&lowbar;file]::basic&lowbar;file
:relfileprefix: ../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;file&period;hpp&gt;`

Move&hyphen;construct a basic&lowbar;file from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_file/2constructor-0f5.adoc[basic&lowbar;file](xref:boost/asio/basic_file.adoc[basic&lowbar;file]&& other) noexcept;
----

[.small]#xref:boost/asio/basic_file/2constructor-0f5.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;file without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/basic_file/2constructor-00.adoc[basic&lowbar;file](xref:boost/asio/basic_file/executor_type.adoc[executor&lowbar;type] const& ex);
----

[.small]#xref:boost/asio/basic_file/2constructor-00.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;file on an existing native file handle&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_file/2constructor-06d.adoc[basic&lowbar;file](
    xref:boost/asio/basic_file/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_file/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;file);
----

[.small]#xref:boost/asio/basic_file/2constructor-06d.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;file without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_file/2constructor-0fc.adoc[basic&lowbar;file](
    ExecutionContext& context,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_file/2constructor-0fc.adoc[_» more&period;&period;&period;_]#

Move&hyphen;construct a basic&lowbar;file from a file of another executor type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
xref:boost/asio/basic_file/2constructor-09.adoc[basic&lowbar;file](
    xref:boost/asio/basic_file.adoc[basic&lowbar;file&lt;Executor1&gt;]&& other,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_file/2constructor-09.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;file&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/basic_file/2constructor-0d.adoc[basic&lowbar;file](
    xref:boost/asio/basic_file/executor_type.adoc[executor&lowbar;type] const& ex,
    std::string const& path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags);
----

[.small]#xref:boost/asio/basic_file/2constructor-0d.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;file&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/basic_file/2constructor-0bd.adoc[basic&lowbar;file](
    xref:boost/asio/basic_file/executor_type.adoc[executor&lowbar;type] const& ex,
    char const* path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags);
----

[.small]#xref:boost/asio/basic_file/2constructor-0bd.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;file on an existing native file&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_file/2constructor-0be.adoc[basic&lowbar;file](
    ExecutionContext& context,
    xref:boost/asio/basic_file/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;file,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_file/2constructor-0be.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;file&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_file/2constructor-06a.adoc[basic&lowbar;file](
    ExecutionContext& context,
    std::string const& path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_file/2constructor-06a.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;file&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_file/2constructor-0cb.adoc[basic&lowbar;file](
    ExecutionContext& context,
    char const* path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_file/2constructor-0cb.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;file object from which the move will occur&period;
| *ex*
| The I&sol;O executor that the file will use, by default, to dispatch handlers for any asynchronous operations performed on the file&period;
| *native&lowbar;file*
| A native file handle&period;
| *context*
| An execution context which provides the I&sol;O executor that the file will use, by default, to dispatch handlers for any asynchronous operations performed on the file&period;
| *path*
| The path name identifying the file to be opened&period;
| *open&lowbar;flags*
| A set of flags that determine how the file should be opened&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
