[#boost-asio-basic_file-open-0b]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_file.adoc[basic&lowbar;file]::open
:relfileprefix: ../../../
:mrdocs:

Open the file using the specified path&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;file&period;hpp&gt;`

Open the file using the specified path&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
xref:boost/asio/basic_file/open-0e7.adoc[open](
    std::string const& path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags);
----

[.small]#xref:boost/asio/basic_file/open-0e7.adoc[_» more&period;&period;&period;_]#

Open the file using the specified path&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
xref:boost/asio/basic_file/open-0e2.adoc[open](
    char const* path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags);
----

[.small]#xref:boost/asio/basic_file/open-0e2.adoc[_» more&period;&period;&period;_]#

Open the file using the specified path&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
boost::system::error&lowbar;code
xref:boost/asio/basic_file/open-0e8.adoc[open](
    std::string const& path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_file/open-0e8.adoc[_» more&period;&period;&period;_]#

Open the file using the specified path&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
boost::system::error&lowbar;code
xref:boost/asio/basic_file/open-0e1.adoc[open](
    char const* path,
    xref:boost/asio/file_base/flags.adoc[file&lowbar;base::flags] open&lowbar;flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_file/open-0e1.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *path*
| The path name identifying the file to be opened&period;
| *open&lowbar;flags*
| A set of flags that determine how the file should be opened&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
