[#boost-asio-associated_allocator-03f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::associated&lowbar;allocator
:relfileprefix: ../../
:mrdocs:

Traits type used to obtain the allocator associated with an object&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;associated&lowbar;allocator&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename T,
    typename Allocator = std::allocator&lt;void&gt;&gt;
struct associated&lowbar;allocator
    : &sol;&ast; implementation-defined &ast;&sol;
----

== Base Classes

[cols=2]
|===
| Name
| Description
| `&sol;&ast; implementation-defined &ast;&sol;`
| 
|===

== Description

A program may specialise this traits type if the `T` template parameter in the specialisation is a user&hyphen;defined type&period; The template parameter `Allocator` shall be a type meeting the Allocator requirements&period;

Specialisations shall meet the following requirements, where `t` is a const reference to an object of type `T,` and `a` is an object of type `Allocator&period;`

* Provide a nested typedef `type` that identifies a type meeting the Allocator requirements&period;
* Provide a noexcept static member function named `get,` callable as `get(t)` and with return type `type` or a (possibly const) reference to `type&period;`
* Provide a noexcept static member function named `get,` callable as `get(t,a)` and with return type `type` or a (possibly const) reference to `type&period;`


[.small]#Created with https://www.mrdocs.com[MrDocs]#
