[#boost-asio-async_read_at-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read&lowbar;at
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read a certain amount of data at the specified offset&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&lowbar;at&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncRandomAccessReadDevice,
    typename Allocator,
    typename CompletionCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncRandomAccessReadDevice::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;at&lowbar;streambuf&lt;
          AsyncRandomAccessReadDevice&gt;&gt;(),
        token, offset, &amp;b,
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
async&lowbar;read&lowbar;at(
    AsyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncRandomAccessReadDevice&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

== Description

This function is used to asynchronously read a certain number of bytes of data from a random access device at the specified offset&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period; The asynchronous operation will continue until one of the following conditions is true&colon;

* The completion&lowbar;condition function object returns 0&period;

This operation is implemented in terms of zero or more calls to the device&apos;s async&lowbar;read&lowbar;some&lowbar;at function&period;

[,cpp]
----
std::size_t completion_condition(
  // Result of latest async_read_some_at operation.
  const boost::system::error_code& error,

  // Number of bytes transferred so far.
  std::size_t bytes_transferred
); 
----
A return value of 0 indicates that the read operation is complete&period; A non&hyphen;zero return value indicates the maximum number of bytes to be read on the next call to the device&apos;s async&lowbar;read&lowbar;some&lowbar;at function&period;

[,cpp]
----
void handler(
  // Result of operation.
  const boost::system::error_code& error,

  // Number of bytes copied into the buffers. If an error
  // occurred, this will be the number of bytes successfully
  // transferred prior to the error.
  std::size_t bytes_transferred
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the `AsyncRandomAccessReadDevice` type&apos;s async&lowbar;read&lowbar;some&lowbar;at operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *d*
| The device from which the data is to be read&period; The type must support the AsyncRandomAccessReadDevice concept&period;
| *offset*
| The offset at which the data will be read&period;
| *b*
| A basic&lowbar;streambuf object into which the data will be read&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
