[#boost-asio-async_connect-09]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;connect
:relfileprefix: ../../
:mrdocs:

Asynchronously establishes a socket connection by trying each endpoint in a sequence&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;connect&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Protocol,
    typename Executor,
    typename Iterator,
    typename IteratorConnectToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;Executor&gt;]&gt;
decltype(async&lowbar;initiate&lt;IteratorConnectToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, Iterator)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;iterator&lowbar;connect&lt;Protocol, Executor&gt;&gt;(),
        token, begin, end, declval&lt;detail&colon;&colon;default&lowbar;connect&lowbar;condition&gt;()))
async&lowbar;connect(
    xref:boost/asio/basic_socket.adoc[basic&lowbar;socket&lt;Protocol, Executor&gt;]& s,
    Iterator begin,
    Iterator end,
    IteratorConnectToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;Executor&gt;(),
    int = 0);
----

== Description

This function attempts to connect a socket to one of a sequence of endpoints&period; It does this by repeated calls to the socket&apos;s `async&lowbar;connect` member function, once for each endpoint in the sequence, until a connection is successfully established&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

[,cpp]
----
void handler(
  // Result of operation. if the sequence is empty, set to
  // boost::asio::error::not_found. Otherwise, contains the
  // error from the last connection attempt.
  const boost::system::error_code& error,

  // On success, an iterator denoting the successfully
  // connected endpoint. Otherwise, the end iterator.
  Iterator iterator
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, Iterator) 
----
== Example
[,cpp]
----
std::vector<tcp::endpoint> endpoints = ...;
tcp::socket s(my_context);
boost::asio::async_connect(s,
    endpoints.begin(), endpoints.end(),
    connect_handler);

// ...

void connect_handler(
    const boost::system::error_code& ec,
    std::vector<tcp::endpoint>::iterator i)
{
  // ...
} 
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the socket&apos;s `async&lowbar;connect` operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The socket to be connected&period; If the socket is already open, it will be closed&period;
| *begin*
| An iterator pointing to the start of a sequence of endpoints&period;
| *end*
| An iterator pointing to the end of a sequence of endpoints&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the connect completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
