[#boost-asio-async_read_until-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read&lowbar;until
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read data into a streambuf until a function object indicates a match&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&lowbar;until&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    typename MatchCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;match&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), match&lowbar;condition))
async&lowbar;read&lowbar;until(
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    MatchCondition match&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

== Description

This function is used to asynchronously read data into the specified streambuf until a user&hyphen;defined match condition function object, when applied to the data contained in the streambuf, indicates a successful match&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period; The asynchronous operation will continue until one of the following conditions is true&colon;

* The match condition function object returns a std&colon;&colon;pair where the second element evaluates to true&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s async&lowbar;read&lowbar;some function, and is known as a _composed operation_&period; If the match condition function object already indicates a match, this asynchronous operation completes immediately&period; The program must ensure that the stream performs no other read operations (such as async&lowbar;read, async&lowbar;read&lowbar;until, the stream&apos;s async&lowbar;read&lowbar;some function, or any other composed operations that perform reads) until this operation completes&period;

[,cpp]
----
pair<iterator, bool> match_condition(iterator begin, iterator end);
----
where `iterator` represents the type&colon;

[,cpp]
----
buffers_iterator<basic_streambuf<Allocator>::const_buffers_type>
----
The iterator parameters `begin` and `end` define the range of bytes to be scanned to determine whether there is a match&period; The `first` member of the return value is an iterator marking one&hyphen;past&hyphen;the&hyphen;end of the bytes that have been consumed by the match function&period; This iterator is used to calculate the `begin` parameter for any subsequent invocation of the match condition&period; The `second` member of the return value is true if a match has been found, false otherwise&period;

[,cpp]
----
void handler(
  // Result of operation.
  const boost::system::error_code& error,

  // The number of bytes in the streambuf's get
  // area that have been fully consumed by the
  // match function. O if an error occurred.
  std::size_t bytes_transferred
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

[NOTE]
After a successful async&lowbar;read&lowbar;until operation, the streambuf may contain additional data beyond that which matched the function object&period; An application will typically leave that data in the streambuf for a subsequent async&lowbar;read&lowbar;until operation to examine&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
[NOTE]
The default implementation of the `is&lowbar;match&lowbar;condition` type trait evaluates to true for function pointers and function objects with a `result&lowbar;type` typedef&period; It must be specialised for other user&hyphen;defined function objects&period;

== Examples
To asynchronously read data into a streambuf until whitespace is encountered&colon;

[,cpp]
----
typedef boost::asio::buffers_iterator<
    boost::asio::streambuf::const_buffers_type> iterator;

std::pair<iterator, bool>
match_whitespace(iterator begin, iterator end)
{
  iterator i = begin;
  while (i != end)
    if (std::isspace(*i++))
      return std::make_pair(i, true);
  return std::make_pair(i, false);
}
...
void handler(const boost::system::error_code& e, std::size_t size);
...
boost::asio::streambuf b;
boost::asio::async_read_until(s, b, match_whitespace, handler);
----
To asynchronously read data into a streambuf until a matching character is found&colon;

[,cpp]
----
class match_char
{
public:
  explicit match_char(char c) : c_(c) {}

  template <typename Iterator>
  std::pair<Iterator, bool> operator()(
      Iterator begin, Iterator end) const
  {
    Iterator i = begin;
    while (i != end)
      if (c_ == *i++)
        return std::make_pair(i, true);
    return std::make_pair(i, false);
  }

private:
  char c_;
};

namespace asio {
  template <> struct is_match_condition<match_char>
    : public boost::true_type {};
} // namespace asio
...
void handler(const boost::system::error_code& e, std::size_t size);
...
boost::asio::streambuf b;
boost::asio::async_read_until(s, b, match_char('a'), handler);
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the `AsyncReadStream` type&apos;s `async&lowbar;read&lowbar;some` operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the AsyncReadStream concept&period;
| *b*
| A streambuf object into which the data will be read&period;
| *match&lowbar;condition*
| The function object to be called to determine whether a match exists&period; The signature of the function object must be&colon;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
