[#boost-asio-async_immediate-01]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;immediate
:relfileprefix: ../../
:mrdocs:

Launch a trivial asynchronous operation that completes immediately&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;immediate&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ExecutionContext,
    typename NullaryToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;ExecutionContext::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;NullaryToken, void()&gt;(
      declval&lt;detail&colon;&colon;initiate&lowbar;immediate&lt;
        typename ExecutionContext&colon;&colon;executor&lowbar;type&gt;&gt;(), token))
async&lowbar;immediate(
    ExecutionContext& ctx,
    NullaryToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename ExecutionContext&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

== Description

The async&lowbar;immediate function is intended for use by composed operations, which can delegate to this operation in order to implement the correct semantics for immediate completion&period;

The completion handler is immediately submitted for execution by calling boost&colon;&colon;asio&colon;&colon;dispatch() on the handler&apos;s associated immediate executor&period;

If the completion handler does not have a customised associated immediate executor, then the handler is submitted as if by calling boost&colon;&colon;asio&colon;&colon;post() on the I&sol;O executor obtained from the supplied execution context&period;

== Completion Signature
[,cpp]
----
void() 
----
== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The execution context used to obtain the asynchronous operation&apos;s I&sol;O executor&period;
| *token*
| The completion token&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
