[#boost-asio-async_write-00]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;write
:relfileprefix: ../../
:mrdocs:

`async&lowbar;write` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;write&period;hpp&gt;`

Start an asynchronous operation to write all of the supplied data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename Allocator,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v1&lt;AsyncWriteStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), transfer&lowbar;all()))
xref:boost/asio/async_write-0d.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_write-0d.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write all of the supplied data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename DynamicBuffer&lowbar;v2,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v2&lt;AsyncWriteStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers),
        transfer&lowbar;all()))
xref:boost/asio/async_write-05.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-05.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write all of the supplied data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename ConstBufferSequence,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lt;AsyncWriteStream&gt;&gt;(),
        token, buffers, transfer&lowbar;all()))
xref:boost/asio/async_write-0a.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    ConstBufferSequence const& buffers,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-0a.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write a certain amount of data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename Allocator,
    typename CompletionCondition,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v1&lt;AsyncWriteStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_write-0f.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_write-0f.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write all of the supplied data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename DynamicBuffer&lowbar;v1,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v1&lt;AsyncWriteStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers),
        transfer&lowbar;all()))
xref:boost/asio/async_write-03.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-03.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write a certain amount of data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename DynamicBuffer&lowbar;v2,
    typename CompletionCondition,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v2&lt;AsyncWriteStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_write-02.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    CompletionCondition completion&lowbar;condition,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-02.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write a certain amount of data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename ConstBufferSequence,
    typename CompletionCondition,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lt;AsyncWriteStream&gt;&gt;(),
        token, buffers,
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_write-06.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    ConstBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-06.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to write a certain amount of data to a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename DynamicBuffer&lowbar;v1,
    typename CompletionCondition,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v1&lt;AsyncWriteStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_write-04.adoc[async&lowbar;write](
    AsyncWriteStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    CompletionCondition completion&lowbar;condition,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_write-04.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream to which the data is to be written&period; The type must support the AsyncWriteStream concept&period;
| *b*
| A basic&lowbar;streambuf object from which data will be written&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the write completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *buffers*
| The dynamic buffer sequence from which data will be written&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period; Successfully written data is automatically consumed from the buffers&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the write operation is complete&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
