[#boost-asio-async_read_until-060]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read&lowbar;until
:relfileprefix: ../../
:mrdocs:

`async&lowbar;read&lowbar;until` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;read&lowbar;until&period;hpp&gt;`

Start an asynchronous operation to read data into a streambuf until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;string&lowbar;v1&lt;
          AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b),
        static&lowbar;cast&lt;std&colon;&colon;string&gt;(delim)))
xref:boost/asio/async_read_until-045.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    std::string&lowbar;view delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/async_read_until-045.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a streambuf until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), delim))
xref:boost/asio/async_read_until-03cd.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    char delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/async_read_until-03cd.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a streambuf until some part of its data matches a regular expression&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    typename Traits,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;expr&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), expr))
xref:boost/asio/async_read_until-065.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    boost::basic&lowbar;regex&lt;char, Traits&gt; const& expr,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/async_read_until-065.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;string&lowbar;v2&lt;
          AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;std&colon;&colon;string&gt;(delim)))
xref:boost/asio/async_read_until-0c.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    std::string&lowbar;view delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-0c.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;v2&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers), delim))
xref:boost/asio/async_read_until-043.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    char delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-043.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until some part of its data matches a regular expression&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    typename Traits,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;expr&lowbar;v2&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers), expr))
xref:boost/asio/async_read_until-00.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    boost::basic&lowbar;regex&lt;char, Traits&gt; const& expr,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-00.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a streambuf until a function object indicates a match&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    typename MatchCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;match&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), match&lowbar;condition))
xref:boost/asio/async_read_until-0f.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    MatchCondition match&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-0f.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;string&lowbar;v1&lt;
          AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;std&colon;&colon;string&gt;(delim)))
xref:boost/asio/async_read_until-031.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    std::string&lowbar;view delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-031.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until it contains a specified delimiter&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers), delim))
xref:boost/asio/async_read_until-02.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    char delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-02.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until a function object indicates a match&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    typename MatchCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;match&lowbar;v2&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers), match&lowbar;condition))
xref:boost/asio/async_read_until-0b.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    MatchCondition match&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-0b.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until some part of its data matches a regular expression&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    typename Traits,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;expr&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers), expr))
xref:boost/asio/async_read_until-01.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    boost::basic&lowbar;regex&lt;char, Traits&gt; const& expr,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-01.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read data into a dynamic buffer sequence until a function object indicates a match&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    typename MatchCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;match&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers),
        match&lowbar;condition))
xref:boost/asio/async_read_until-03c4.adoc[async&lowbar;read&lowbar;until](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    MatchCondition match&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read_until-03c4.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the AsyncReadStream concept&period;
| *b*
| A streambuf object into which the data will be read&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *delim*
| The delimiter string&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *expr*
| The regular expression&period;
| *buffers*
| The dynamic buffer sequence into which the data will be read&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *match&lowbar;condition*
| The function object to be called to determine whether a match exists&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
