[#boost-asio-async_read_at-04]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read&lowbar;at
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read a certain amount of data at the specified offset&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;read&lowbar;at&period;hpp&gt;`

Start an asynchronous operation to read a certain amount of data at the specified offset&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncRandomAccessReadDevice,
    typename Allocator,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncRandomAccessReadDevice::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;at&lowbar;streambuf&lt;
          AsyncRandomAccessReadDevice&gt;&gt;(),
        token, offset, &amp;b, transfer&lowbar;all()))
xref:boost/asio/async_read_at-0d.adoc[async&lowbar;read&lowbar;at](
    AsyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncRandomAccessReadDevice&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_at-0d.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data at the specified offset&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncRandomAccessReadDevice,
    typename MutableBufferSequence,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncRandomAccessReadDevice::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;at&lt;AsyncRandomAccessReadDevice&gt;&gt;(),
        token, offset, buffers, transfer&lowbar;all()))
xref:boost/asio/async_read_at-09.adoc[async&lowbar;read&lowbar;at](
    AsyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncRandomAccessReadDevice&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_at-09.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data at the specified offset&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncRandomAccessReadDevice,
    typename Allocator,
    typename CompletionCondition,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncRandomAccessReadDevice::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;at&lowbar;streambuf&lt;
          AsyncRandomAccessReadDevice&gt;&gt;(),
        token, offset, &amp;b,
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read_at-05.adoc[async&lowbar;read&lowbar;at](
    AsyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncRandomAccessReadDevice&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_at-05.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data at the specified offset&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncRandomAccessReadDevice,
    typename MutableBufferSequence,
    typename CompletionCondition,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncRandomAccessReadDevice::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;at&lt;AsyncRandomAccessReadDevice&gt;&gt;(),
        token, offset, buffers,
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read_at-01.adoc[async&lowbar;read&lowbar;at](
    AsyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncRandomAccessReadDevice&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read_at-01.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *d*
| The device from which the data is to be read&period; The type must support the AsyncRandomAccessReadDevice concept&period;
| *offset*
| The offset at which the data will be read&period;
| *b*
| A basic&lowbar;streambuf object into which the data will be read&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *buffers*
| One or more buffers into which the data will be read&period; The sum of the buffer sizes indicates the maximum number of bytes to read from the device&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
