[#boost-asio-async_read_until-02]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read&lowbar;until
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read data into a dynamic buffer sequence until it contains a specified delimiter&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&lowbar;until&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;until&lowbar;delim&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers), delim))
async&lowbar;read&lowbar;until(
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    char delim,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

== Description

This function is used to asynchronously read data into the specified dynamic buffer sequence until the dynamic buffer sequence&apos;s get area contains the specified delimiter&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period; The asynchronous operation will continue until one of the following conditions is true&colon;

* The get area of the dynamic buffer sequence contains the specified delimiter&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s async&lowbar;read&lowbar;some function, and is known as a _composed operation_&period; If the dynamic buffer sequence&apos;s get area already contains the delimiter, this asynchronous operation completes immediately&period; The program must ensure that the stream performs no other read operations (such as async&lowbar;read, async&lowbar;read&lowbar;until, the stream&apos;s async&lowbar;read&lowbar;some function, or any other composed operations that perform reads) until this operation completes&period;

[,cpp]
----
void handler(
  // Result of operation.
  const boost::system::error_code& error,

  // The number of bytes in the dynamic buffer sequence's
  // get area up to and including the delimiter.
  std::size_t bytes_transferred
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
[NOTE]
After a successful async&lowbar;read&lowbar;until operation, the dynamic buffer sequence may contain additional data beyond the delimiter&period; An application will typically leave that data in the dynamic buffer sequence for a subsequent async&lowbar;read&lowbar;until operation to examine&period;

== Example
To asynchronously read data into a `std&colon;&colon;string` until a newline is encountered&colon;

[,cpp]
----
std::string data;
...
void handler(const boost::system::error_code& e, std::size_t size)
{
  if (!e)
  {
    std::string line = data.substr(0, n);
    data.erase(0, n);
    ...
  }
}
...
boost::asio::async_read_until(s, data, '\n', handler); 
----
After the `async&lowbar;read&lowbar;until` operation completes successfully, the buffer `data` contains the delimiter&colon;

[,cpp]
----
{ 'a', 'b', ..., 'c', '\n', 'd', 'e', ... } 
----
The call to `substr` then extracts the data up to and including the delimiter, so that the string `line` contains&colon;

[,cpp]
----
{ 'a', 'b', ..., 'c', '\n' } 
----
After the call to `erase,` the remaining data is left in the buffer `data` as follows&colon;

[,cpp]
----
{ 'd', 'e', ... } 
----
This data may be the start of a new line, to be extracted by a subsequent `async&lowbar;read&lowbar;until` operation&period;

== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the `AsyncReadStream` type&apos;s `async&lowbar;read&lowbar;some` operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the AsyncReadStream concept&period;
| *buffers*
| The dynamic buffer sequence into which the data will be read&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *delim*
| The delimiter character&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
