[#boost-asio-async_read-02]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read a certain amount of data from a stream&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;read&period;hpp&gt;`

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b), transfer&lowbar;all()))
xref:boost/asio/async_read-0a.adoc[async&lowbar;read](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read-0a.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v2&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers), transfer&lowbar;all()))
xref:boost/asio/async_read-09fb.adoc[async&lowbar;read](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-09fb.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename MutableBufferSequence,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lt;AsyncReadStream&gt;&gt;(),
        token, buffers, transfer&lowbar;all()))
xref:boost/asio/async_read-06.adoc[async&lowbar;read](
    AsyncReadStream& s,
    MutableBufferSequence const& buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-06.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename Allocator,
    typename CompletionCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read-05.adoc[async&lowbar;read](
    AsyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

[.small]#xref:boost/asio/async_read-05.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers), transfer&lowbar;all()))
xref:boost/asio/async_read-01.adoc[async&lowbar;read](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-01.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    typename CompletionCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v2&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v2&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read-09f2.adoc[async&lowbar;read](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-09f2.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename MutableBufferSequence,
    typename CompletionCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lt;AsyncReadStream&gt;&gt;(),
        token, buffers,
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read-00.adoc[async&lowbar;read](
    AsyncReadStream& s,
    MutableBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-00.adoc[_» more&period;&period;&period;_]#

Start an asynchronous operation to read a certain amount of data from a stream&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename DynamicBuffer&lowbar;v1,
    typename CompletionCondition,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lowbar;dynbuf&lowbar;v1&lt;AsyncReadStream&gt;&gt;(),
        token, static&lowbar;cast&lt;DynamicBuffer&lowbar;v1&amp;&amp;&gt;(buffers),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
xref:boost/asio/async_read-0f.adoc[async&lowbar;read](
    AsyncReadStream& s,
    DynamicBuffer&lowbar;v1&& buffers,
    CompletionCondition completion&lowbar;condition,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/async_read-0f.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the AsyncReadStream concept&period;
| *b*
| A basic&lowbar;streambuf object into which the data will be read&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *buffers*
| The dynamic buffer sequence into which the data will be read&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
