[#boost-asio-async_read-06]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;read
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to read a certain amount of data from a stream&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncReadStream,
    typename MutableBufferSequence,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncReadStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;read&lt;AsyncReadStream&gt;&gt;(),
        token, buffers, transfer&lowbar;all()))
async&lowbar;read(
    AsyncReadStream& s,
    MutableBufferSequence const& buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;
      typename AsyncReadStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0,
    int = 0);
----

== Description

This function is used to asynchronously read a certain number of bytes of data from a stream&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period; The asynchronous operation will continue until one of the following conditions is true&colon;

* The supplied buffers are full&period; That is, the bytes transferred is equal to the sum of the buffer sizes&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s async&lowbar;read&lowbar;some function, and is known as a _composed operation_&period; The program must ensure that the stream performs no other read operations (such as async&lowbar;read, the stream&apos;s async&lowbar;read&lowbar;some function, or any other composed operations that perform reads) until this operation completes&period;

[,cpp]
----
void handler(
  // Result of operation.
  const boost::system::error_code& error,

  // Number of bytes copied into the buffers. If an error
  // occurred, this will be the number of bytes successfully
  // transferred prior to the error.
  std::size_t bytes_transferred
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
== Example
To read into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
boost::asio::async_read(s, boost::asio::buffer(data, size), handler);
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on reading into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

[NOTE]
This overload is equivalent to calling&colon;

[,cpp]
----
boost::asio::async_read(
    s, buffers,
    boost::asio::transfer_all(),
    handler); 
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the `AsyncReadStream` type&apos;s `async&lowbar;read&lowbar;some` operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the AsyncReadStream concept&period;
| *buffers*
| One or more buffers into which the data will be read&period; The sum of the buffer sizes indicates the maximum number of bytes to read from the stream&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
