[#boost-asio-async_write-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::async&lowbar;write
:relfileprefix: ../../
:mrdocs:

Start an asynchronous operation to write a certain amount of data to a stream&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;write&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename AsyncWriteStream,
    typename Allocator,
    typename CompletionCondition,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;AsyncWriteStream::executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
      void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
        declval&lt;detail&colon;&colon;initiate&lowbar;async&lowbar;write&lowbar;dynbuf&lowbar;v1&lt;AsyncWriteStream&gt;&gt;(),
        token, basic&lowbar;streambuf&lowbar;ref&lt;Allocator&gt;(b),
        static&lowbar;cast&lt;CompletionCondition&amp;&amp;&gt;(completion&lowbar;condition)))
async&lowbar;write(
    AsyncWriteStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;typename AsyncWriteStream&colon;&colon;executor&lowbar;type&gt;(),
    int = 0);
----

== Description

This function is used to asynchronously write a certain number of bytes of data to a stream&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period; The asynchronous operation will continue until one of the following conditions is true&colon;

* All of the data in the supplied basic&lowbar;streambuf has been written&period;
* The completion&lowbar;condition function object returns 0&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s async&lowbar;write&lowbar;some function, and is known as a _composed operation_&period; The program must ensure that the stream performs no other write operations (such as async&lowbar;write, the stream&apos;s async&lowbar;write&lowbar;some function, or any other composed operations that perform writes) until this operation completes&period;

[,cpp]
----
std::size_t completion_condition(
  // Result of latest async_write_some operation.
  const boost::system::error_code& error,

  // Number of bytes transferred so far.
  std::size_t bytes_transferred
); 
----
A return value of 0 indicates that the write operation is complete&period; A non&hyphen;zero return value indicates the maximum number of bytes to be written on the next call to the stream&apos;s async&lowbar;write&lowbar;some function&period;

[,cpp]
----
void handler(
  // Result of operation.
  const boost::system::error_code& error,

  // Number of bytes written from the buffers. If an error
  // occurred, this will be less than the sum of the buffer sizes.
  std::size_t bytes_transferred
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`

if they are also supported by the `AsyncWriteStream` type&apos;s `async&lowbar;write&lowbar;some` operation&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream to which the data is to be written&period; The type must support the AsyncWriteStream concept&period;
| *b*
| A basic&lowbar;streambuf object from which data will be written&period; Ownership of the streambuf is retained by the caller, which must guarantee that it remains valid until the completion handler is called&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the write operation is complete&period; The signature of the function object must be&colon;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the write completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
