[#boost-asio-cancel_after-0e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::cancel&lowbar;after
:relfileprefix: ../../
:mrdocs:

`cancel&lowbar;after` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;cancel&lowbar;after&period;hpp&gt;`

Create a partial completion token adapter that cancels an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Rep,
    typename Period&gt;
xref:boost/asio/partial_cancel_after.adoc[partial&lowbar;cancel&lowbar;after&lt;std::chrono::steady&lowbar;clock&gt;]
xref:boost/asio/cancel_after-09f.adoc[cancel&lowbar;after](
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

[.small]#xref:boost/asio/cancel_after-09f.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Rep,
    typename Period,
    typename CompletionToken&gt;
xref:boost/asio/cancel_after_t.adoc[cancel&lowbar;after&lowbar;t&lt;decay&lowbar;t&lt;CompletionToken&gt;, std::chrono::steady&lowbar;clock&gt;]
xref:boost/asio/cancel_after-095.adoc[cancel&lowbar;after](
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_after-095.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Rep,
    typename Period,
    typename CompletionToken&gt;
xref:boost/asio/cancel_after_t.adoc[cancel&lowbar;after&lowbar;t&lt;decay&lowbar;t&lt;CompletionToken&gt;, std::chrono::steady&lowbar;clock&gt;]
xref:boost/asio/cancel_after-0b.adoc[cancel&lowbar;after](
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_after-0b.adoc[_» more&period;&period;&period;_]#

Create a partial completion token adapter that cancels an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Rep,
    typename Period&gt;
xref:boost/asio/partial_cancel_after_timer.adoc[partial&lowbar;cancel&lowbar;after&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]
xref:boost/asio/cancel_after-02.adoc[cancel&lowbar;after](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

[.small]#xref:boost/asio/cancel_after-02.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Rep,
    typename Period,
    typename CompletionToken&gt;
xref:boost/asio/cancel_after_timer.adoc[cancel&lowbar;after&lowbar;timer&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock, WaitTraits, Executor&gt;]
xref:boost/asio/cancel_after-0d.adoc[cancel&lowbar;after](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_after-0d.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete before the specified relative timeout has elapsed&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Rep,
    typename Period,
    typename CompletionToken&gt;
xref:boost/asio/cancel_after_timer.adoc[cancel&lowbar;after&lowbar;timer&lt;decay&lowbar;t&lt;CompletionToken&gt;, std::chrono::steady&lowbar;clock&gt;]
xref:boost/asio/cancel_after-00.adoc[cancel&lowbar;after](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_after-00.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
