[#boost-asio-cancel_at-08]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::cancel&lowbar;at
:relfileprefix: ../../
:mrdocs:

`cancel&lowbar;at` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;cancel&lowbar;at&period;hpp&gt;`

Create a partial completion token adapter that cancels an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/partial_cancel_at.adoc[partial&lowbar;cancel&lowbar;at&lt;Clock&gt;]
xref:boost/asio/cancel_at-0d.adoc[cancel&lowbar;at](
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

[.small]#xref:boost/asio/cancel_at-0d.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename CompletionToken,
    typename Clock,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/cancel_at_t.adoc[cancel&lowbar;at&lowbar;t&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock&gt;]
xref:boost/asio/cancel_at-01.adoc[cancel&lowbar;at](
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_at-01.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename CompletionToken,
    typename Clock,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/cancel_at_t.adoc[cancel&lowbar;at&lowbar;t&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock&gt;]
xref:boost/asio/cancel_at-07.adoc[cancel&lowbar;at](
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_at-07.adoc[_» more&period;&period;&period;_]#

Create a partial completion token adapter that cancels an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/partial_cancel_at_timer.adoc[partial&lowbar;cancel&lowbar;at&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]
xref:boost/asio/cancel_at-0b.adoc[cancel&lowbar;at](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

[.small]#xref:boost/asio/cancel_at-0b.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename CompletionToken,
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/cancel_at_timer.adoc[cancel&lowbar;at&lowbar;timer&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock, WaitTraits, Executor&gt;]
xref:boost/asio/cancel_at-03.adoc[cancel&lowbar;at](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_at-03.adoc[_» more&period;&period;&period;_]#

Adapt a `completion&lowbar;token` to cancel an operation if not complete by the specified absolute time&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename CompletionToken,
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Duration&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/cancel_at_timer.adoc[cancel&lowbar;at&lowbar;timer&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock, WaitTraits, Executor&gt;]
xref:boost/asio/cancel_at-05.adoc[cancel&lowbar;at](
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type,
    CompletionToken&& completion&lowbar;token);
----

[.small]#xref:boost/asio/cancel_at-05.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
