[#boost-asio-cancel_after-09f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::cancel&lowbar;after
:relfileprefix: ../../
:mrdocs:

Create a partial completion token adapter that cancels an operation if not complete before the specified relative timeout has elapsed&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;cancel&lowbar;after&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Rep,
    typename Period&gt;
xref:boost/asio/partial_cancel_after.adoc[partial&lowbar;cancel&lowbar;after&lt;std::chrono::steady&lowbar;clock&gt;]
cancel&lowbar;after(
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

== Description

== Thread Safety
When an asynchronous operation is used with cancel&lowbar;after, a timer async&lowbar;wait operation is performed in parallel to the main operation&period; If this parallel async&lowbar;wait completes first, a cancellation request is emitted to cancel the main operation&period; Consequently, the application must ensure that the asynchronous operation is performed within an implicit or explicit strand&period;

== Return Value

A function object type that adapts a `completion&lowbar;token` to cancel an operation after a timeout&period;


[.small]#Created with https://www.mrdocs.com[MrDocs]#
