[#boost-asio-cancel_at-0b]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::cancel&lowbar;at
:relfileprefix: ../../
:mrdocs:

Create a partial completion token adapter that cancels an operation if not complete by the specified absolute time&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;cancel&lowbar;at&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Duration&gt;
xref:boost/asio/partial_cancel_at_timer.adoc[partial&lowbar;cancel&lowbar;at&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]
cancel&lowbar;at(
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::time&lowbar;point&lt;Clock, Duration&gt; const& expiry,
    xref:boost/asio/cancellation_type_t.adoc[cancellation&lowbar;type&lowbar;t] cancel&lowbar;type = cancellation&lowbar;type&colon;&colon;terminal);
----

== Description

== Thread Safety
When an asynchronous operation is used with cancel&lowbar;at, a timer async&lowbar;wait operation is performed in parallel to the main operation&period; If this parallel async&lowbar;wait completes first, a cancellation request is emitted to cancel the main operation&period; Consequently, the application must ensure that the asynchronous operation is performed within an implicit or explicit strand&period;

== Return Value

A function object type that adapts a `completion&lowbar;token` to cancel an operation at a given time&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *timer*
| Provides waitable timer functionality&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
