[#boost-asio-cancel_after-0d]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::cancel&lowbar;after
:relfileprefix: ../../
:mrdocs:

Adapt a `completion&lowbar;token` to cancel an operation if not complete before the specified relative timeout has elapsed&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;cancel&lowbar;after&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Clock,
    typename WaitTraits,
    typename Executor,
    typename Rep,
    typename Period,
    typename CompletionToken&gt;
&lsqb;&lsqb;nodiscard&rsqb;&rsqb;
xref:boost/asio/cancel_after_timer.adoc[cancel&lowbar;after&lowbar;timer&lt;decay&lowbar;t&lt;CompletionToken&gt;, Clock, WaitTraits, Executor&gt;]
cancel&lowbar;after(
    xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer&lt;Clock, WaitTraits, Executor&gt;]& timer,
    chrono::duration&lt;Rep, Period&gt; const& timeout,
    CompletionToken&& completion&lowbar;token);
----

== Description

== Thread Safety
When an asynchronous operation is used with cancel&lowbar;after, a timer async&lowbar;wait operation is performed in parallel to the main operation&period; If this parallel async&lowbar;wait completes first, a cancellation request is emitted to cancel the main operation&period; Consequently, the application must ensure that the asynchronous operation is performed within an implicit or explicit strand&period;

== Return Value

A `completion&lowbar;token` adapter that cancels an operation after a timeout&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *timer*
| Provides waitable timer functionality&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
