[#boost-asio-co_spawn-0b0]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::co&lowbar;spawn
:relfileprefix: ../../
:mrdocs:

Spawn a new coroutined&hyphen;based thread of execution&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;co&lowbar;spawn&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Executor,
    typename AwaitableExecutor,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(std::exception&lowbar;ptr)&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;Executor&gt;::type&gt;
auto
co&lowbar;spawn(
    Executor const& ex,
    xref:boost/asio/awaitable.adoc[awaitable&lt;void, AwaitableExecutor&gt;] a,
    CompletionToken&& token,
    int = 0);
----

== Description

[,cpp]
----
void handler(std::exception_ptr); 
----
== Completion Signature
[,cpp]
----
void(std::exception_ptr) 
----
== Example
[,cpp]
----
boost::asio::awaitable<void> echo(tcp::socket socket)
{
  try
  {
    char data[1024];
    for (;;)
    {
      std::size_t n = co_await socket.async_read_some(
          boost::asio::buffer(data), boost::asio::use_awaitable);

      co_await boost::asio::async_write(socket,
          boost::asio::buffer(data, n), boost::asio::use_awaitable);
    }
  }
  catch (const std::exception& e)
  {
    std::cerr << "Exception: " << e.what() << "\n";
  }
}

// ...

boost::asio::co_spawn(my_executor,
  echo(std::move(my_tcp_socket)),
  boost::asio::detached);
----
== Per&hyphen;Operation Cancellation
The new thread of execution is created with a cancellation state that supports `cancellation&lowbar;type&colon;&colon;terminal` values only&period; To change the cancellation state, call boost&colon;&colon;asio&colon;&colon;this&lowbar;coro&colon;&colon;reset&lowbar;cancellation&lowbar;state&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The executor that will be used to schedule the new thread of execution&period;
| *a*
| The boost&colon;&colon;asio&colon;&colon;awaitable object that is the result of calling the coroutine&apos;s entry point function&period;
| *token*
| The `completion&lowbar;token` that will handle the notification that the thread of execution has completed&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
