[#boost-asio-co_spawn-07]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::co&lowbar;spawn
:relfileprefix: ../../
:mrdocs:

Spawn a new coroutined&hyphen;based thread of execution&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;co&lowbar;spawn&period;hpp&gt;`

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ExecutionContext,
    typename AwaitableExecutor,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(std::exception&lowbar;ptr)&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;ExecutionContext::executor&lowbar;type&gt;::type&gt;
auto
xref:boost/asio/co_spawn-0c6.adoc[co&lowbar;spawn](
    ExecutionContext& ctx,
    xref:boost/asio/awaitable.adoc[awaitable&lt;void, AwaitableExecutor&gt;] a,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-0c6.adoc[_» more&period;&period;&period;_]#

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ExecutionContext,
    typename F,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;&sol;&ast; implementation-defined &ast;&sol;::type&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;ExecutionContext::executor&lowbar;type&gt;::type&gt;
auto
xref:boost/asio/co_spawn-0c1.adoc[co&lowbar;spawn](
    ExecutionContext& ctx,
    F&& f,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-0c1.adoc[_» more&period;&period;&period;_]#

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Executor,
    typename AwaitableExecutor,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(std::exception&lowbar;ptr)&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;Executor&gt;::type&gt;
auto
xref:boost/asio/co_spawn-0b0.adoc[co&lowbar;spawn](
    Executor const& ex,
    xref:boost/asio/awaitable.adoc[awaitable&lt;void, AwaitableExecutor&gt;] a,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-0b0.adoc[_» more&period;&period;&period;_]#

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Executor,
    typename F,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;&sol;&ast; implementation-defined &ast;&sol;::type&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;Executor&gt;::type&gt;
auto
xref:boost/asio/co_spawn-0c8.adoc[co&lowbar;spawn](
    Executor const& ex,
    F&& f,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-0c8.adoc[_» more&period;&period;&period;_]#

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ExecutionContext,
    typename T,
    typename AwaitableExecutor,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(std::exception&lowbar;ptr, T)&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;ExecutionContext::executor&lowbar;type&gt;::type&gt;
auto
xref:boost/asio/co_spawn-0bc.adoc[co&lowbar;spawn](
    ExecutionContext& ctx,
    xref:boost/asio/awaitable.adoc[awaitable&lt;T, AwaitableExecutor&gt;] a,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-0bc.adoc[_» more&period;&period;&period;_]#

Spawn a new coroutined&hyphen;based thread of execution&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Executor,
    typename T,
    typename AwaitableExecutor,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(std::exception&lowbar;ptr, T)&gt;] CompletionToken = boost::asio::default&lowbar;completion&lowbar;token&lt;Executor&gt;::type&gt;
auto
xref:boost/asio/co_spawn-03.adoc[co&lowbar;spawn](
    Executor const& ex,
    xref:boost/asio/awaitable.adoc[awaitable&lt;T, AwaitableExecutor&gt;] a,
    CompletionToken&& token,
    int = 0);
----

[.small]#xref:boost/asio/co_spawn-03.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *ctx*
| An execution context that will provide the executor to be used to schedule the new thread of execution&period;
| *a*
| The boost&colon;&colon;asio&colon;&colon;awaitable object that is the result of calling the coroutine&apos;s entry point function&period;
| *token*
| The `completion&lowbar;token` that will handle the notification that the thread of execution has completed&period; The function signature of the completion handler must be&colon;
| *f*
| A nullary function object with a return type of the form `boost&colon;&colon;asio&colon;&colon;awaitable&lt;R,E&gt;` that will be used as the coroutine&apos;s entry point&period;
| *ex*
| The executor that will be used to schedule the new thread of execution&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
