[#boost-asio-is_dynamic_buffer]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::is&lowbar;dynamic&lowbar;buffer
:relfileprefix: ../../
:mrdocs:

Trait to determine whether a type satisfies the DynamicBuffer requirements&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;buffer&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct is&lowbar;dynamic&lowbar;buffer
    : xref:boost/asio/is_dynamic_buffer_v1.adoc[boost::asio::is&lowbar;dynamic&lowbar;buffer&lowbar;v1&lt;T&gt;]
----

== Base Classes

[cols=2]
|===
| Name
| Description
| `xref:boost/asio/is_dynamic_buffer_v1.adoc[boost::asio::is&lowbar;dynamic&lowbar;buffer&lowbar;v1&lt;T&gt;]`
| Trait to determine whether a type satisfies the DynamicBuffer&lowbar;v1 requirements&period;
|===

== Description

If `BOOST&lowbar;ASIO&lowbar;NO&lowbar;DYNAMIC&lowbar;BUFFER&lowbar;V1` is not defined, determines whether the type satisfies the DynamicBuffer&lowbar;v1 requirements&period; Otherwise, if `BOOST&lowbar;ASIO&lowbar;NO&lowbar;DYNAMIC&lowbar;BUFFER&lowbar;V1` is defined, determines whether the type satisfies the DynamicBuffer&lowbar;v2 requirements&period;


[.small]#Created with https://www.mrdocs.com[MrDocs]#
