[#boost-asio-is_disposition]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::is&lowbar;disposition
:relfileprefix: ../../
:mrdocs:

Trait used for testing whether a type satisfies the requirements of a disposition&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;disposition&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct is&lowbar;disposition
    : &sol;&ast; implementation-defined &ast;&sol;
----

== Base Classes

[cols=2]
|===
| Name
| Description
| `&sol;&ast; implementation-defined &ast;&sol;`
| 
|===

== Description

To be a valid disposition, a type must be nothrow default&hyphen;constructible, nothrow move&hyphen;constructible, nothrow move&hyphen;assignable, and there must be a specialisation of the disposition&lowbar;traits template for the type that provides the following static member functions&colon;

* `not&lowbar;an&lowbar;error&colon;` Takes an argument of type and returns a `bool&period;`
* `throw&lowbar;exception&colon;` Takes an argument of type &period; The caller of this function must not pass a disposition value for which `not&lowbar;an&lowbar;error` returns true&period; This function must not return&period;
* `to&lowbar;exception&lowbar;ptr&colon;` Takes an argument of type and returns a value of type `std&colon;&colon;exception&lowbar;ptr&period;`


[.small]#Created with https://www.mrdocs.com[MrDocs]#
