[#boost-asio-read_until-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::read&lowbar;until
:relfileprefix: ../../
:mrdocs:

Read data into a streambuf until some part of the data it contains matches a regular expression&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&lowbar;until&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncReadStream,
    typename Allocator,
    typename Traits&gt;
size&lowbar;t
read&lowbar;until(
    SyncReadStream& s,
    xref:boost/asio/basic_streambuf.adoc[boost::asio::basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    boost::basic&lowbar;regex&lt;char, Traits&gt; const& expr,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to read data into the specified streambuf until the streambuf&apos;s get area contains some data that matches a regular expression&period; The call will block until one of the following conditions is true&colon;

* A substring of the streambuf&apos;s get area matches the regular expression&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s read&lowbar;some function&period; If the streambuf&apos;s get area already contains data that matches the regular expression, the function returns immediately&period;

[NOTE]
After a successful read&lowbar;until operation, the streambuf may contain additional data beyond that which matched the regular expression&period; An application will typically leave that data in the streambuf for a subsequent read&lowbar;until operation to examine&period;

== Return Value

The number of bytes in the streambuf&apos;s get area up to and including the substring that matches the regular expression&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the SyncReadStream concept&period;
| *b*
| A streambuf object into which the data will be read&period;
| *expr*
| The regular expression&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
