[#boost-asio-read-02]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::read
:relfileprefix: ../../
:mrdocs:

Attempt to read a certain amount of data from a stream before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncReadStream,
    typename DynamicBuffer&lowbar;v2,
    typename CompletionCondition&gt;
size&lowbar;t
read(
    SyncReadStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    CompletionCondition completion&lowbar;condition,
    boost::system::error&lowbar;code& ec,
    int = 0,
    int = 0);
----

== Description

This function is used to read a certain number of bytes of data from a stream&period; The call will block until one of the following conditions is true&colon;

* The specified dynamic buffer sequence is full (that is, it has reached maximum size)&period;
* The completion&lowbar;condition function object returns 0&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s read&lowbar;some function&period;

[,cpp]
----
std::size_t completion_condition(
  // Result of latest read_some operation.
  const boost::system::error_code& error,

  // Number of bytes transferred so far.
  std::size_t bytes_transferred
); 
----
A return value of 0 indicates that the read operation is complete&period; A non&hyphen;zero return value indicates the maximum number of bytes to be read on the next call to the stream&apos;s read&lowbar;some function&period;

== Return Value

The number of bytes read&period; If an error occurs, returns the total number of bytes successfully transferred prior to the error&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the SyncReadStream concept&period;
| *buffers*
| The dynamic buffer sequence into which the data will be read&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
