[#boost-asio-read_at-06]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::read&lowbar;at
:relfileprefix: ../../
:mrdocs:

Attempt to read a certain amount of data at the specified offset before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&lowbar;at&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename MutableBufferSequence&gt;
size&lowbar;t
read&lowbar;at(
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers);
----

== Description

This function is used to read a certain number of bytes of data from a random access device at the specified offset&period; The call will block until one of the following conditions is true&colon;

* The supplied buffers are full&period; That is, the bytes transferred is equal to the sum of the buffer sizes&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the device&apos;s read&lowbar;some&lowbar;at function&period;

== Example
To read into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
boost::asio::read_at(d, 42, boost::asio::buffer(data, size)); 
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on reading into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

[NOTE]
This overload is equivalent to calling&colon;

[,cpp]
----
boost::asio::read_at(
    d, 42, buffers,
    boost::asio::transfer_all()); 
----
== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes transferred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *d*
| The device from which the data is to be read&period; The type must support the SyncRandomAccessReadDevice concept&period;
| *offset*
| The offset at which the data will be read&period;
| *buffers*
| One or more buffers into which the data will be read&period; The sum of the buffer sizes indicates the maximum number of bytes to read from the device&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
