[#boost-asio-read_at-0a]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::read&lowbar;at
:relfileprefix: ../../
:mrdocs:

Attempt to read a certain amount of data at the specified offset before returning&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;read&lowbar;at&period;hpp&gt;`

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename Allocator&gt;
size&lowbar;t
xref:boost/asio/read_at-0d4.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b);
----

[.small]#xref:boost/asio/read_at-0d4.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/read_at-06.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers);
----

[.small]#xref:boost/asio/read_at-06.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename Allocator&gt;
size&lowbar;t
xref:boost/asio/read_at-04f.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/read_at-04f.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/read_at-0b5.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/read_at-0b5.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename Allocator,
    typename CompletionCondition&gt;
size&lowbar;t
xref:boost/asio/read_at-0da.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    int = 0);
----

[.small]#xref:boost/asio/read_at-0da.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename MutableBufferSequence,
    typename CompletionCondition&gt;
size&lowbar;t
xref:boost/asio/read_at-0b2.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    int = 0);
----

[.small]#xref:boost/asio/read_at-0b2.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename Allocator,
    typename CompletionCondition&gt;
size&lowbar;t
xref:boost/asio/read_at-049.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    CompletionCondition completion&lowbar;condition,
    boost::system::error&lowbar;code& ec,
    int = 0);
----

[.small]#xref:boost/asio/read_at-049.adoc[_» more&period;&period;&period;_]#

Attempt to read a certain amount of data at the specified offset before returning&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessReadDevice,
    typename MutableBufferSequence,
    typename CompletionCondition&gt;
size&lowbar;t
xref:boost/asio/read_at-01.adoc[read&lowbar;at](
    SyncRandomAccessReadDevice& d,
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    boost::system::error&lowbar;code& ec,
    int = 0);
----

[.small]#xref:boost/asio/read_at-01.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

* The number of bytes transferred&period;
* The number of bytes read&period; If an error occurs, returns the total number of bytes successfully transferred prior to the error&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *d*
| The device from which the data is to be read&period; The type must support the SyncRandomAccessReadDevice concept&period;
| *offset*
| The offset at which the data will be read&period;
| *b*
| The basic&lowbar;streambuf object into which the data will be read&period;
| *buffers*
| One or more buffers into which the data will be read&period; The sum of the buffer sizes indicates the maximum number of bytes to read from the device&period;
| *ec*
| Set to indicate what error occurred, if any&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
