[#boost-asio-read-076]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::read
:relfileprefix: ../../
:mrdocs:

Attempt to read a certain amount of data from a stream before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;read&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncReadStream,
    typename MutableBufferSequence,
    typename CompletionCondition&gt;
size&lowbar;t
read(
    SyncReadStream& s,
    MutableBufferSequence const& buffers,
    CompletionCondition completion&lowbar;condition,
    int = 0,
    int = 0);
----

== Description

This function is used to read a certain number of bytes of data from a stream&period; The call will block until one of the following conditions is true&colon;

* The supplied buffers are full&period; That is, the bytes transferred is equal to the sum of the buffer sizes&period;
* The completion&lowbar;condition function object returns 0&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s read&lowbar;some function&period;

[,cpp]
----
std::size_t completion_condition(
  // Result of latest read_some operation.
  const boost::system::error_code& error,

  // Number of bytes transferred so far.
  std::size_t bytes_transferred
); 
----
A return value of 0 indicates that the read operation is complete&period; A non&hyphen;zero return value indicates the maximum number of bytes to be read on the next call to the stream&apos;s read&lowbar;some function&period;

== Example
To read into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
boost::asio::read(s, boost::asio::buffer(data, size),
    boost::asio::transfer_at_least(32)); 
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on reading into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes transferred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream from which the data is to be read&period; The type must support the SyncReadStream concept&period;
| *buffers*
| One or more buffers into which the data will be read&period; The sum of the buffer sizes indicates the maximum number of bytes to read from the stream&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the read operation is complete&period; The signature of the function object must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
