[#boost-asio-write-044]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::write
:relfileprefix: ../../
:mrdocs:

Write all of the supplied data to a stream before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;write&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncWriteStream,
    typename Allocator&gt;
size&lowbar;t
write(
    SyncWriteStream& s,
    xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf&lt;Allocator&gt;]& b,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to write a certain number of bytes of data to a stream&period; The call will block until one of the following conditions is true&colon;

* All of the data in the supplied basic&lowbar;streambuf has been written&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s write&lowbar;some function&period;

[NOTE]
This overload is equivalent to calling&colon;

[,cpp]
----
boost::asio::write(
    s, b,
    boost::asio::transfer_all(), ec); 
----
== Return Value

The number of bytes transferred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream to which the data is to be written&period; The type must support the SyncWriteStream concept&period;
| *b*
| The basic&lowbar;streambuf object from which data will be written&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
