[#boost-asio-write-04e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::write
:relfileprefix: ../../
:mrdocs:

Write a certain amount of data to a stream before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;write&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncWriteStream,
    typename DynamicBuffer&lowbar;v2,
    typename CompletionCondition&gt;
size&lowbar;t
write(
    SyncWriteStream& s,
    DynamicBuffer&lowbar;v2 buffers,
    CompletionCondition completion&lowbar;condition,
    boost::system::error&lowbar;code& ec,
    int = 0,
    int = 0);
----

== Description

This function is used to write a certain number of bytes of data to a stream&period; The call will block until one of the following conditions is true&colon;

* All of the data in the supplied dynamic buffer sequence has been written&period;
* The completion&lowbar;condition function object returns 0&period;

This operation is implemented in terms of zero or more calls to the stream&apos;s write&lowbar;some function&period;

[,cpp]
----
std::size_t completion_condition(
  // Result of latest write_some operation.
  const boost::system::error_code& error,

  // Number of bytes transferred so far.
  std::size_t bytes_transferred
); 
----
A return value of 0 indicates that the write operation is complete&period; A non&hyphen;zero return value indicates the maximum number of bytes to be written on the next call to the stream&apos;s write&lowbar;some function&period;

== Return Value

The number of bytes written&period; If an error occurs, returns the total number of bytes successfully transferred prior to the error&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *s*
| The stream to which the data is to be written&period; The type must support the SyncWriteStream concept&period;
| *buffers*
| The dynamic buffer sequence from which data will be written&period; Successfully written data is automatically consumed from the buffers&period;
| *completion&lowbar;condition*
| The function object to be called to determine whether the write operation is complete&period; The signature of the function object must be&colon;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
