[#boost-asio-write_at-0ea]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::write&lowbar;at
:relfileprefix: ../../
:mrdocs:

Write all of the supplied data at the specified offset before returning&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;write&lowbar;at&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename SyncRandomAccessWriteDevice,
    typename ConstBufferSequence&gt;
size&lowbar;t
write&lowbar;at(
    SyncRandomAccessWriteDevice& d,
    std::uint64&lowbar;t offset,
    ConstBufferSequence const& buffers);
----

== Description

This function is used to write a certain number of bytes of data to a random access device at a specified offset&period; The call will block until one of the following conditions is true&colon;

* All of the data in the supplied buffers has been written&period; That is, the bytes transferred is equal to the sum of the buffer sizes&period;
* An error occurred&period;

This operation is implemented in terms of zero or more calls to the device&apos;s write&lowbar;some&lowbar;at function&period;

== Example
To write a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
boost::asio::write_at(d, 42, boost::asio::buffer(data, size)); 
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on writing multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

[NOTE]
This overload is equivalent to calling&colon;

[,cpp]
----
boost::asio::write_at(
    d, offset, buffers,
    boost::asio::transfer_all()); 
----
== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes transferred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *d*
| The device to which the data is to be written&period; The type must support the SyncRandomAccessWriteDevice concept&period;
| *offset*
| The offset at which the data will be written&period;
| *buffers*
| One or more buffers containing the data to be written&period; The sum of the buffer sizes indicates the maximum number of bytes to write to the device&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
