[#boost-asio-basic_signal_set-2constructor-043495]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_signal_set.adoc[basic&lowbar;signal&lowbar;set]::basic&lowbar;signal&lowbar;set
:relfileprefix: ../../../
:mrdocs:

Construct a signal set and add three signals&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;signal&lowbar;set&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;signal&lowbar;set(
    xref:boost/asio/basic_signal_set/executor_type.adoc[executor&lowbar;type] const& ex,
    int signal&lowbar;number&lowbar;1,
    int signal&lowbar;number&lowbar;2,
    int signal&lowbar;number&lowbar;3);
----

== Description

This constructor creates a signal set and registers for three signals&period;

[NOTE]
This constructor is equivalent to performing&colon;

[,cpp]
----
boost::asio::signal_set signals(ex);
signals.add(signal_number_1);
signals.add(signal_number_2);
signals.add(signal_number_3); 
----
== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The I&sol;O executor that the signal set will use, by default, to dispatch handlers for any asynchronous operations performed on the signal set&period;
| *signal&lowbar;number&lowbar;1*
| The first signal number to be added&period;
| *signal&lowbar;number&lowbar;2*
| The second signal number to be added&period;
| *signal&lowbar;number&lowbar;3*
| The third signal number to be added&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
