[#boost-asio-basic_signal_set-add-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_signal_set.adoc[basic&lowbar;signal&lowbar;set]::add
:relfileprefix: ../../../
:mrdocs:

`add` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;signal&lowbar;set&period;hpp&gt;`

Add a signal to a signal&lowbar;set&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
xref:boost/asio/basic_signal_set/add-01.adoc[add](int signal&lowbar;number);
----

[.small]#xref:boost/asio/basic_signal_set/add-01.adoc[_» more&period;&period;&period;_]#

Add a signal to a signal&lowbar;set with the specified flags&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
xref:boost/asio/basic_signal_set/add-05.adoc[add](
    int signal&lowbar;number,
    xref:boost/asio/signal_set_base/flags_t.adoc[flags&lowbar;t] f);
----

[.small]#xref:boost/asio/basic_signal_set/add-05.adoc[_» more&period;&period;&period;_]#

Add a signal to a signal&lowbar;set&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
boost::system::error&lowbar;code
xref:boost/asio/basic_signal_set/add-0c.adoc[add](
    int signal&lowbar;number,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_signal_set/add-0c.adoc[_» more&period;&period;&period;_]#

Add a signal to a signal&lowbar;set with the specified flags&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
boost::system::error&lowbar;code
xref:boost/asio/basic_signal_set/add-03.adoc[add](
    int signal&lowbar;number,
    xref:boost/asio/signal_set_base/flags_t.adoc[flags&lowbar;t] f,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_signal_set/add-03.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *signal&lowbar;number*
| The signal to be added to the set&period;
| *f*
| Flags to modify the behaviour of the specified signal&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
