[#boost-asio-basic_signal_set-async_wait]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_signal_set.adoc[basic&lowbar;signal&lowbar;set]::async&lowbar;wait
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous operation to wait for a signal to be delivered&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;signal&lowbar;set&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, int)&gt;] SignalToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;SignalToken, void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, int)&gt;(
        declval&lt;initiate&lowbar;async&lowbar;wait&gt;(), token))
async&lowbar;wait(SignalToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

== Description

This function may be used to initiate an asynchronous wait against the signal set&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

For each call to async&lowbar;wait(), the completion handler will be called exactly once&period; The completion handler will be called when&colon;

* One of the registered signals in the signal set occurs&semi; or
* The signal set was cancelled, in which case the handler is passed the error code boost&colon;&colon;asio&colon;&colon;error&colon;&colon;operation&lowbar;aborted&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error, // Result of operation.
  int signal_number // Indicates which signal occurred.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, int) 
----
== Per&hyphen;Operation Cancellation
This asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`
* `cancellation&lowbar;type&colon;&colon;total`

[NOTE]
Unlike the POSIX function `signal,` `async&lowbar;wait` executes its completion handler as specified in the `async&lowbar;op&lowbar;requirements`&period; This means it places no async&hyphen;signal safety restrictions on what work can be performed in a completion handler&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the wait completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
