[#boost-asio-basic_socket_acceptor-2constructor-0ba]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]::basic&lowbar;socket&lowbar;acceptor
:relfileprefix: ../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&lowbar;acceptor&period;hpp&gt;`

Move&hyphen;construct a basic&lowbar;socket&lowbar;acceptor from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/2constructor-05.adoc[basic&lowbar;socket&lowbar;acceptor](xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]&& other) noexcept;
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-05.adoc[_» more&period;&period;&period;_]#

Construct an acceptor without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/basic_socket_acceptor/2constructor-06.adoc[basic&lowbar;socket&lowbar;acceptor](xref:boost/asio/basic_socket_acceptor/executor_type.adoc[executor&lowbar;type] const& ex);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-06.adoc[_» more&period;&period;&period;_]#

Construct an open acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/2constructor-094.adoc[basic&lowbar;socket&lowbar;acceptor](
    xref:boost/asio/basic_socket_acceptor/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_socket_acceptor/protocol_type.adoc[protocol&lowbar;type] const& protocol);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-094.adoc[_» more&period;&period;&period;_]#

Construct an acceptor without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_socket_acceptor/2constructor-03.adoc[basic&lowbar;socket&lowbar;acceptor](
    ExecutionContext& context,
    int = 0);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-03.adoc[_» more&period;&period;&period;_]#

Move&hyphen;construct a basic&lowbar;socket&lowbar;acceptor from an acceptor of another protocol type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Protocol1,
    typename Executor1&gt;
xref:boost/asio/basic_socket_acceptor/2constructor-0f.adoc[basic&lowbar;socket&lowbar;acceptor](
    xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor&lt;Protocol1, Executor1&gt;]&& other,
    int = 0);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-0f.adoc[_» more&period;&period;&period;_]#

Construct an acceptor opened on the given endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/2constructor-0b3.adoc[basic&lowbar;socket&lowbar;acceptor](
    xref:boost/asio/basic_socket_acceptor/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint,
    bool reuse&lowbar;addr = true);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-0b3.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;socket&lowbar;acceptor on an existing native acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/2constructor-02.adoc[basic&lowbar;socket&lowbar;acceptor](
    xref:boost/asio/basic_socket_acceptor/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_socket_acceptor/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/basic_socket_acceptor/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;acceptor);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-02.adoc[_» more&period;&period;&period;_]#

Construct an open acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_socket_acceptor/2constructor-09f.adoc[basic&lowbar;socket&lowbar;acceptor](
    ExecutionContext& context,
    xref:boost/asio/basic_socket_acceptor/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-09f.adoc[_» more&period;&period;&period;_]#

Construct an acceptor opened on the given endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_socket_acceptor/2constructor-08.adoc[basic&lowbar;socket&lowbar;acceptor](
    ExecutionContext& context,
    xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint,
    bool reuse&lowbar;addr = true,
    int = 0);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-08.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;socket&lowbar;acceptor on an existing native acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_socket_acceptor/2constructor-00.adoc[basic&lowbar;socket&lowbar;acceptor](
    ExecutionContext& context,
    xref:boost/asio/basic_socket_acceptor/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/basic_socket_acceptor/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;acceptor,
    int = 0);
----

[.small]#xref:boost/asio/basic_socket_acceptor/2constructor-00.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;socket&lowbar;acceptor object from which the move will occur&period;
| *ex*
| The I&sol;O executor that the acceptor will use, by default, to dispatch handlers for any asynchronous operations performed on the acceptor&period;
| *protocol*
| An object specifying protocol parameters to be used&period;
| *context*
| An execution context which provides the I&sol;O executor that the acceptor will use, by default, to dispatch handlers for any asynchronous operations performed on the acceptor&period;
| *endpoint*
| An endpoint on the local machine on which the acceptor will listen for new connections&period;
| *reuse&lowbar;addr*
| Whether the constructor should set the socket option socket&lowbar;base&colon;&colon;reuse&lowbar;address&period;
| *native&lowbar;acceptor*
| A native acceptor&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
