[#boost-asio-basic_socket_acceptor-accept-07]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]::accept
:relfileprefix: ../../../
:mrdocs:

Accept a new connection and obtain the endpoint of the peer

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&lowbar;acceptor&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
void
accept(
    xref:boost/asio/basic_socket.adoc[basic&lowbar;socket&lt;protocol&lowbar;type, Executor1&gt;]& peer,
    xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type]& peer&lowbar;endpoint);
----

== Description

This function is used to accept a new connection from a peer into the given socket, and additionally provide the endpoint of the remote peer&period; The function call will block until a new connection has been accepted successfully or an error occurs&period;

== Example
[,cpp]
----
boost::asio::ip::tcp::acceptor acceptor(my_context);
...
boost::asio::ip::tcp::socket socket(my_context);
boost::asio::ip::tcp::endpoint endpoint;
acceptor.accept(socket, endpoint);
----
== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *peer*
| The socket into which the new connection will be accepted&period;
| *peer&lowbar;endpoint*
| An endpoint object which will receive the endpoint of the remote peer&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
