[#boost-asio-basic_socket_acceptor-accept-0c80]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]::accept
:relfileprefix: ../../../
:mrdocs:

Accept a new connection&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&lowbar;acceptor&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
Protocol::socket::rebind&lowbar;executor&lt;Executor1&gt;::other
accept(
    Executor1 const& ex,
    xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type]& peer&lowbar;endpoint,
    int = 0);
----

== Description

This function is used to accept a new connection from a peer&period; The function call will block until a new connection has been accepted successfully or an error occurs&period;

This overload requires that the Protocol template parameter satisfy the AcceptableProtocol type requirements&period;

== Example
[,cpp]
----
boost::asio::ip::tcp::acceptor acceptor(my_context);
...
boost::asio::ip::tcp::endpoint endpoint;
boost::asio::ip::tcp::socket socket(
    acceptor.accept(my_context2, endpoint));
----
== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

A socket object representing the newly accepted connection&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The I&sol;O executor object to be used for the newly accepted socket&period;
| *peer&lowbar;endpoint*
| An endpoint object into which the endpoint of the remote peer will be written&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
