[#boost-asio-basic_socket_acceptor-async_accept-09]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]::async&lowbar;accept
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous accept&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&lowbar;acceptor&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Protocol1,
    typename Executor1,
    typename AcceptToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;AcceptToken, void (boost&colon;&colon;system&colon;&colon;error&lowbar;code)&gt;(
        declval&lt;initiate&lowbar;async&lowbar;accept&gt;(), token,
        &amp;peer, static&lowbar;cast&lt;endpoint&lowbar;type&ast;&gt;(0)))
async&lowbar;accept(
    xref:boost/asio/basic_socket.adoc[basic&lowbar;socket&lt;Protocol1, Executor1&gt;]& peer,
    AcceptToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;(),
    int = 0);
----

== Description

This function is used to asynchronously accept a new connection into a socket, and additionally obtain the endpoint of the remote peer&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error // Result of operation.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code) 
----
== Example
[,cpp]
----
void accept_handler(const boost::system::error_code& error)
{
  if (!error)
  {
    // Accept succeeded.
  }
}

...

boost::asio::ip::tcp::acceptor acceptor(my_context);
...
boost::asio::ip::tcp::socket socket(my_context);
acceptor.async_accept(socket, accept_handler);
----
== Per&hyphen;Operation Cancellation
On POSIX or Windows operating systems, this asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`
* `cancellation&lowbar;type&colon;&colon;total`

== Parameters

[cols=2]
|===
| Name
| Description
| *peer*
| The socket into which the new connection will be accepted&period; Ownership of the peer object is retained by the caller, which must guarantee that it is valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the accept completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
