[#boost-asio-basic_socket_acceptor-local_endpoint-075]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_socket_acceptor.adoc[basic&lowbar;socket&lowbar;acceptor]::local&lowbar;endpoint
:relfileprefix: ../../../
:mrdocs:

Get the local endpoint of the acceptor&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;socket&lowbar;acceptor&period;hpp&gt;`

Get the local endpoint of the acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type]
xref:boost/asio/basic_socket_acceptor/local_endpoint-079.adoc[local&lowbar;endpoint]() const;
----

[.small]#xref:boost/asio/basic_socket_acceptor/local_endpoint-079.adoc[_» more&period;&period;&period;_]#

Get the local endpoint of the acceptor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_socket_acceptor/endpoint_type.adoc[endpoint&lowbar;type]
xref:boost/asio/basic_socket_acceptor/local_endpoint-0b.adoc[local&lowbar;endpoint](boost::system::error&lowbar;code& ec) const;
----

[.small]#xref:boost/asio/basic_socket_acceptor/local_endpoint-0b.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

* An object that represents the local endpoint of the acceptor&period;
* An object that represents the local endpoint of the acceptor&period; Returns a default&hyphen;constructed endpoint object if an error occurred and the error handler did not throw an exception&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
