[#boost-asio-immediate_executor_binder-2constructor-090]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder]::immediate&lowbar;executor&lowbar;binder
:relfileprefix: ../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;bind&lowbar;immediate&lowbar;executor&period;hpp&gt;`

Copy constructor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/immediate_executor_binder/2constructor-04.adoc[immediate&lowbar;executor&lowbar;binder](xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder] const& other);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-04.adoc[_» more&period;&period;&period;_]#

Move constructor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/immediate_executor_binder/2constructor-00.adoc[immediate&lowbar;executor&lowbar;binder](xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder]&& other);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-00.adoc[_» more&period;&period;&period;_]#

Construct a copy, but specify a different immediate executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/immediate_executor_binder/2constructor-05.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder/immediate_executor_type.adoc[immediate&lowbar;executor&lowbar;type] const& e,
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder] const& other);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-05.adoc[_» more&period;&period;&period;_]#

Move construct the target object, but specify a different immediate executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/immediate_executor_binder/2constructor-02.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder/immediate_executor_type.adoc[immediate&lowbar;executor&lowbar;type] const& e,
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder]&& other);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-02.adoc[_» more&period;&period;&period;_]#

Construct a immediate executor wrapper for the specified object&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
xref:boost/asio/immediate_executor_binder/2constructor-0f.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder/immediate_executor_type.adoc[immediate&lowbar;executor&lowbar;type] const& e,
    U&& u);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-0f.adoc[_» more&period;&period;&period;_]#

Construct a copy of a different immediate executor wrapper type, but specify a different immediate executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename U,
    typename OtherExecutor&gt;
xref:boost/asio/immediate_executor_binder/2constructor-0c1.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder/immediate_executor_type.adoc[immediate&lowbar;executor&lowbar;type] const& e,
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder&lt;U, OtherExecutor&gt;] const& other,
    int = 0);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-0c1.adoc[_» more&period;&period;&period;_]#

Move construct from a different immediate executor wrapper type, but specify a different immediate executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename U,
    typename OtherExecutor&gt;
xref:boost/asio/immediate_executor_binder/2constructor-01.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder/immediate_executor_type.adoc[immediate&lowbar;executor&lowbar;type] const& e,
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder&lt;U, OtherExecutor&gt;]&& other,
    int = 0);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-01.adoc[_» more&period;&period;&period;_]#

Construct a copy of a different immediate executor wrapper type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename U,
    typename OtherExecutor&gt;
xref:boost/asio/immediate_executor_binder/2constructor-0cd.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder&lt;U, OtherExecutor&gt;] const& other,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-0cd.adoc[_» more&period;&period;&period;_]#

Move construct from a different immediate executor wrapper type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename U,
    typename OtherExecutor&gt;
xref:boost/asio/immediate_executor_binder/2constructor-091.adoc[immediate&lowbar;executor&lowbar;binder](
    xref:boost/asio/immediate_executor_binder.adoc[immediate&lowbar;executor&lowbar;binder&lt;U, OtherExecutor&gt;]&& other,
    int = 0,
    int = 0);
----

[.small]#xref:boost/asio/immediate_executor_binder/2constructor-091.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
