[#boost-asio-basic_readable_pipe-2constructor-076]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_readable_pipe.adoc[basic&lowbar;readable&lowbar;pipe]::basic&lowbar;readable&lowbar;pipe
:relfileprefix: ../../../
:mrdocs:

Move&hyphen;construct a basic&lowbar;readable&lowbar;pipe from a pipe of another executor type&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;readable&lowbar;pipe&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
basic&lowbar;readable&lowbar;pipe(
    xref:boost/asio/basic_readable_pipe.adoc[basic&lowbar;readable&lowbar;pipe&lt;Executor1&gt;]&& other,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

== Description

This constructor moves a pipe from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;readable&lowbar;pipe(const` executor&lowbar;type&amp;) constructor&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;readable&lowbar;pipe object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
