[#boost-asio-basic_readable_pipe-operator_assign-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_readable_pipe.adoc[basic&lowbar;readable&lowbar;pipe]::operator&equals;
:relfileprefix: ../../../
:mrdocs:

Move&hyphen;assign a basic&lowbar;readable&lowbar;pipe from another&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;readable&lowbar;pipe&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_readable_pipe.adoc[basic&lowbar;readable&lowbar;pipe]&
operator&equals;(xref:boost/asio/basic_readable_pipe.adoc[basic&lowbar;readable&lowbar;pipe]&& other);
----

== Description

This assignment operator moves a pipe from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;readable&lowbar;pipe(const` executor&lowbar;type&amp;) constructor&period;

== Return Value

Reference to the current object

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;readable&lowbar;pipe object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
