[#boost-asio-basic_stream_socket-async_read_some]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_stream_socket.adoc[basic&lowbar;stream&lowbar;socket]::async&lowbar;read&lowbar;some
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous read&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;stream&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename MutableBufferSequence,
    xref:boost/asio/completion_token_for.adoc[boost::asio::completion&lowbar;token&lowbar;for&lt;void(boost::system::error&lowbar;code, size&lowbar;t)&gt;] ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;receive&gt;(), token,
          buffers, socket&lowbar;base&colon;&colon;message&lowbar;flags(0)))
async&lowbar;read&lowbar;some(
    MutableBufferSequence const& buffers,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

== Description

This function is used to asynchronously read data from the stream socket&period; socket&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error, // Result of operation.
  std::size_t bytes_transferred // Number of bytes read.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
[NOTE]
The read operation may not read all of the requested number of bytes&period; Consider using the xref:boost/asio/async_read-02.adoc[`async&lowbar;read`] function if you need to ensure that the requested amount of data is read before the asynchronous operation completes&period;

== Example
To read into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
socket.async_read_some(boost::asio::buffer(data, size), handler);
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on reading into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

== Per&hyphen;Operation Cancellation
On POSIX or Windows operating systems, this asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`
* `cancellation&lowbar;type&colon;&colon;total`

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be read&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the read completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], xref:boost/asio/use_awaitable.adoc[`use&lowbar;awaitable`], `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
