[#boost-asio-basic_stream_socket-send-01]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_stream_socket.adoc[basic&lowbar;stream&lowbar;socket]::send
:relfileprefix: ../../../
:mrdocs:

Send some data on the socket&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;stream&lowbar;socket&period;hpp&gt;`

Send some data on the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_stream_socket/send-0e2.adoc[send](ConstBufferSequence const& buffers);
----

[.small]#xref:boost/asio/basic_stream_socket/send-0e2.adoc[_» more&period;&period;&period;_]#

Send some data on the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_stream_socket/send-0e8.adoc[send](
    ConstBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags);
----

[.small]#xref:boost/asio/basic_stream_socket/send-0e8.adoc[_» more&period;&period;&period;_]#

Send some data on the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_stream_socket/send-05.adoc[send](
    ConstBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_stream_socket/send-05.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

* The number of bytes sent&period;
* The number of bytes sent&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more data buffers to be sent on the socket&period;
| *flags*
| Flags specifying how the send call is to be made&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
