[#boost-asio-basic_raw_socket-2constructor-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::basic&lowbar;raw&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;raw&lowbar;socket on an existing native socket&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;raw&lowbar;socket(
    xref:boost/asio/basic_raw_socket/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_raw_socket/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/basic_raw_socket/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;socket);
----

== Description

This constructor creates a raw socket object to hold an existing native socket&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
| *protocol*
| An object specifying protocol parameters to be used&period;
| *native&lowbar;socket*
| The new underlying socket implementation&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
