[#boost-asio-basic_raw_socket-async_send_to-03]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::async&lowbar;send&lowbar;to
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous send&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

Start an asynchronous send&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ConstBufferSequence,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;send&lowbar;to&gt;(), token, buffers,
          destination, socket&lowbar;base&colon;&colon;message&lowbar;flags(0)))
xref:boost/asio/basic_raw_socket/async_send_to-01.adoc[async&lowbar;send&lowbar;to](
    ConstBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type] const& destination,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/basic_raw_socket/async_send_to-01.adoc[_» more&period;&period;&period;_]#

Start an asynchronous send&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename ConstBufferSequence,
    typename WriteToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;WriteToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;send&lowbar;to&gt;(), token,
          buffers, destination, flags))
xref:boost/asio/basic_raw_socket/async_send_to-07.adoc[async&lowbar;send&lowbar;to](
    ConstBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type] const& destination,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    WriteToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/basic_raw_socket/async_send_to-07.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more data buffers to be sent to the remote endpoint&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *destination*
| The remote endpoint to which the data will be sent&period; Copies will be made of the endpoint as required&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the send completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *flags*
| Flags specifying how the send call is to be made&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
