[#boost-asio-basic_raw_socket-async_receive_from-0d9]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::async&lowbar;receive&lowbar;from
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous receive&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

Start an asynchronous receive&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename MutableBufferSequence,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;receive&lowbar;from&gt;(), token, buffers,
          &amp;sender&lowbar;endpoint, socket&lowbar;base&colon;&colon;message&lowbar;flags(0)))
xref:boost/asio/basic_raw_socket/async_receive_from-02.adoc[async&lowbar;receive&lowbar;from](
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/basic_raw_socket/async_receive_from-02.adoc[_» more&period;&period;&period;_]#

Start an asynchronous receive&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename MutableBufferSequence,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;receive&lowbar;from&gt;(), token,
          buffers, &amp;sender&lowbar;endpoint, flags))
xref:boost/asio/basic_raw_socket/async_receive_from-0d6.adoc[async&lowbar;receive&lowbar;from](
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/basic_raw_socket/async_receive_from-0d6.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *sender&lowbar;endpoint*
| An endpoint object that receives the endpoint of the remote sender of the data&period; Ownership of the sender&lowbar;endpoint object is retained by the caller, which must guarantee that it is valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the receive completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *flags*
| Flags specifying how the receive call is to be made&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
