[#boost-asio-basic_raw_socket-operator_assign-02]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::operator&equals;
:relfileprefix: ../../../
:mrdocs:

Move&hyphen;assign a basic&lowbar;raw&lowbar;socket from another&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]&
operator&equals;(xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]&& other);
----

== Description

This assignment operator moves a raw socket from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;raw&lowbar;socket(const` executor&lowbar;type&amp;) constructor&period;

== Return Value

Reference to the current object

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;raw&lowbar;socket object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
