[#boost-asio-basic_raw_socket-receive_from-04]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::receive&lowbar;from
:relfileprefix: ../../../
:mrdocs:

Receive raw data with the endpoint of the sender&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

Receive raw data with the endpoint of the sender&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/receive_from-0e.adoc[receive&lowbar;from](
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint);
----

[.small]#xref:boost/asio/basic_raw_socket/receive_from-0e.adoc[_» more&period;&period;&period;_]#

Receive raw data with the endpoint of the sender&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/receive_from-07.adoc[receive&lowbar;from](
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags);
----

[.small]#xref:boost/asio/basic_raw_socket/receive_from-07.adoc[_» more&period;&period;&period;_]#

Receive raw data with the endpoint of the sender&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/receive_from-09.adoc[receive&lowbar;from](
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_raw_socket/receive_from-09.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes received&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period;
| *sender&lowbar;endpoint*
| An endpoint object that receives the endpoint of the remote sender of the data&period;
| *flags*
| Flags specifying how the receive call is to be made&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
