[#boost-asio-basic_raw_socket-send_to-08]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_raw_socket.adoc[basic&lowbar;raw&lowbar;socket]::send&lowbar;to
:relfileprefix: ../../../
:mrdocs:

Send raw data to the specified endpoint&period;

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;raw&lowbar;socket&period;hpp&gt;`

Send raw data to the specified endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/send_to-05.adoc[send&lowbar;to](
    ConstBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type] const& destination);
----

[.small]#xref:boost/asio/basic_raw_socket/send_to-05.adoc[_» more&period;&period;&period;_]#

Send raw data to the specified endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/send_to-096.adoc[send&lowbar;to](
    ConstBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type] const& destination,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags);
----

[.small]#xref:boost/asio/basic_raw_socket/send_to-096.adoc[_» more&period;&period;&period;_]#

Send raw data to the specified endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_raw_socket/send_to-097.adoc[send&lowbar;to](
    ConstBufferSequence const& buffers,
    xref:boost/asio/basic_raw_socket/endpoint_type.adoc[endpoint&lowbar;type] const& destination,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_raw_socket/send_to-097.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes sent&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more data buffers to be sent to the remote endpoint&period;
| *destination*
| The remote endpoint to which the data will be sent&period;
| *flags*
| Flags specifying how the send call is to be made&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
