[#boost-asio-basic_random_access_file-2constructor-0d1]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file]::basic&lowbar;random&lowbar;access&lowbar;file
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;random&lowbar;access&lowbar;file on an existing native file&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;random&lowbar;access&lowbar;file&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;random&lowbar;access&lowbar;file(
    xref:boost/asio/basic_random_access_file/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_random_access_file/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;file);
----

== Description

This constructor initialises a random&hyphen;access file object to hold an existing native file&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The I&sol;O executor that the file will use, by default, to dispatch handlers for any asynchronous operations performed on the file&period;
| *native&lowbar;file*
| The new underlying file implementation&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
