[#boost-asio-basic_random_access_file-2constructor-01]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file]::basic&lowbar;random&lowbar;access&lowbar;file
:relfileprefix: ../../../
:mrdocs:

Move&hyphen;construct a basic&lowbar;random&lowbar;access&lowbar;file from a file of another executor type&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;random&lowbar;access&lowbar;file&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
basic&lowbar;random&lowbar;access&lowbar;file(
    xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file&lt;Executor1&gt;]&& other,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

== Description

This constructor moves a random&hyphen;access file from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;random&lowbar;access&lowbar;file(const` executor&lowbar;type&amp;) constructor&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;random&lowbar;access&lowbar;file object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
