[#boost-asio-basic_random_access_file-2constructor-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file]::basic&lowbar;random&lowbar;access&lowbar;file
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;random&lowbar;access&lowbar;file without opening it&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;random&lowbar;access&lowbar;file&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
basic&lowbar;random&lowbar;access&lowbar;file(
    ExecutionContext& context,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

== Description

This constructor initialises a file without opening it&period; The file needs to be opened before data can be read from or or written to it&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *context*
| An execution context which provides the I&sol;O executor that the file will use, by default, to dispatch handlers for any asynchronous operations performed on the file&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
