[#boost-asio-basic_random_access_file-read_some_at-0e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file]::read&lowbar;some&lowbar;at
:relfileprefix: ../../../
:mrdocs:

Read some data from the handle at the specified offset&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;random&lowbar;access&lowbar;file&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
read&lowbar;some&lowbar;at(
    std::uint64&lowbar;t offset,
    MutableBufferSequence const& buffers,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to read data from the random&hyphen;access handle&period; The function call will block until one or more bytes of data has been read successfully, or until an error occurs&period;

[NOTE]
The read&lowbar;some operation may not read all of the requested number of bytes&period; Consider using the xref:boost/asio/read_at-0a.adoc[`read&lowbar;at`] function if you need to ensure that the requested amount of data is read before the blocking operation completes&period;

== Return Value

The number of bytes read&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *offset*
| The offset at which the data will be read&period;
| *buffers*
| One or more buffers into which the data will be read&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
