[#boost-asio-basic_random_access_file-write_some_at-0b]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_random_access_file.adoc[basic&lowbar;random&lowbar;access&lowbar;file]::write&lowbar;some&lowbar;at
:relfileprefix: ../../../
:mrdocs:

Write some data to the handle at the specified offset&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;random&lowbar;access&lowbar;file&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
write&lowbar;some&lowbar;at(
    std::uint64&lowbar;t offset,
    ConstBufferSequence const& buffers,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to write data to the random&hyphen;access handle&period; The function call will block until one or more bytes of the data has been written successfully, or until an error occurs&period;

[NOTE]
The write&lowbar;some operation may not write all of the data to the file&period; Consider using the xref:boost/asio/write_at-05c.adoc[`write&lowbar;at`] function if you need to ensure that all data is written before the blocking operation completes&period;

== Return Value

The number of bytes written&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *offset*
| The offset at which the data will be written&period;
| *buffers*
| One or more data buffers to be written to the handle&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
