[#boost-asio-basic_streambuf-prepare]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_streambuf.adoc[basic&lowbar;streambuf]::prepare
:relfileprefix: ../../../
:mrdocs:

Get a list of buffers that represents the output sequence, with the given size&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;streambuf&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_streambuf/mutable_buffers_type.adoc[mutable&lowbar;buffers&lowbar;type]
prepare(size&lowbar;t n);
----

== Description

Ensures that the output sequence can accommodate `n` characters, reallocating character array objects as necessary&period;

[NOTE]
The returned object is invalidated by any `basic&lowbar;streambuf` member function that modifies the input sequence or output sequence&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `std&colon;&colon;length&lowbar;error`
| If &period;
|===

== Return Value

An object of type `mutable&lowbar;buffers&lowbar;type` that satisfies MutableBufferSequence requirements, representing character array objects at the start of the output sequence such that the sum of the buffer sizes is `n&period;`


[.small]#Created with https://www.mrdocs.com[MrDocs]#
