[#boost-asio-windows-basic_object_handle-2constructor-0e]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/windows.adoc[windows]::xref:boost/asio/windows/basic_object_handle.adoc[basic&lowbar;object&lowbar;handle]::basic&lowbar;object&lowbar;handle
:relfileprefix: ../../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;windows&sol;basic&lowbar;object&lowbar;handle&period;hpp&gt;`

Move&hyphen;construct an object handle from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/windows/basic_object_handle/2constructor-04bf.adoc[basic&lowbar;object&lowbar;handle](xref:boost/asio/windows/basic_object_handle.adoc[basic&lowbar;object&lowbar;handle]&& other);
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-04bf.adoc[_» more&period;&period;&period;_]#

Construct an object handle without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/windows/basic_object_handle/2constructor-05.adoc[basic&lowbar;object&lowbar;handle](xref:boost/asio/windows/basic_object_handle/executor_type.adoc[executor&lowbar;type] const& ex);
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-05.adoc[_» more&period;&period;&period;_]#

Construct an object handle on an existing native handle&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/windows/basic_object_handle/2constructor-08f.adoc[basic&lowbar;object&lowbar;handle](
    xref:boost/asio/windows/basic_object_handle/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/windows/basic_object_handle/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;handle);
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-08f.adoc[_» more&period;&period;&period;_]#

Construct an object handle without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/windows/basic_object_handle/2constructor-089.adoc[basic&lowbar;object&lowbar;handle](
    ExecutionContext& context,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-089.adoc[_» more&period;&period;&period;_]#

Move&hyphen;construct an object handle from a handle of another executor type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor1&gt;
xref:boost/asio/windows/basic_object_handle/2constructor-0f.adoc[basic&lowbar;object&lowbar;handle](
    xref:boost/asio/windows/basic_object_handle.adoc[basic&lowbar;object&lowbar;handle&lt;Executor1&gt;]&& other,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-0f.adoc[_» more&period;&period;&period;_]#

Construct an object handle on an existing native handle&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/windows/basic_object_handle/2constructor-04bc.adoc[basic&lowbar;object&lowbar;handle](
    ExecutionContext& context,
    xref:boost/asio/windows/basic_object_handle/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;handle,
    int = 0);
----

[.small]#xref:boost/asio/windows/basic_object_handle/2constructor-04bc.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other object handle object from which the move will occur&period;
| *ex*
| The I&sol;O executor that the object handle will use, by default, to dispatch handlers for any asynchronous operations performed on the object handle&period;
| *native&lowbar;handle*
| The new underlying handle implementation&period;
| *context*
| An execution context which provides the I&sol;O executor that the object handle will use, by default, to dispatch handlers for any asynchronous operations performed on the object handle&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
