[#boost-asio-windows-basic_object_handle-2constructor-04bf]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/windows.adoc[windows]::xref:boost/asio/windows/basic_object_handle.adoc[basic&lowbar;object&lowbar;handle]::basic&lowbar;object&lowbar;handle
:relfileprefix: ../../../../
:mrdocs:

Move&hyphen;construct an object handle from another&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;windows&sol;basic&lowbar;object&lowbar;handle&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;object&lowbar;handle(xref:boost/asio/windows/basic_object_handle.adoc[basic&lowbar;object&lowbar;handle]&& other);
----

== Description

This constructor moves an object handle from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;object&lowbar;handle(const` executor&lowbar;type&amp;) constructor&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other object handle object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
