[#boost-asio-basic_system_executor-defer]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_system_executor.adoc[basic&lowbar;system&lowbar;executor]::defer
:relfileprefix: ../../../
:mrdocs:

Request the system executor to invoke the given function object&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;system&lowbar;executor&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Function,
    typename OtherAllocator&gt;
void
defer(
    Function&& f,
    OtherAllocator const& a);
----

== Description

This function is used to ask the executor to execute the given function object&period; The function object will never be executed inside this function&period; Instead, it will be scheduled to run on an unspecified system thread pool&period;

[,cpp]
----
void function(); 
----
== Parameters

[cols=2]
|===
| Name
| Description
| *f*
| The function object to be called&period; The executor will make a copy of the handler object as required&period; The function signature of the function object must be&colon;
| *a*
| An allocator that may be used by the executor to allocate the internal storage needed for function invocation&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
