[#boost-asio-ip-basic_resolver_query-2constructor-01]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::xref:boost/asio/ip/basic_resolver_query.adoc[basic&lowbar;resolver&lowbar;query]::basic&lowbar;resolver&lowbar;query
:relfileprefix: ../../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;ip&sol;basic&lowbar;resolver&lowbar;query&period;hpp&gt;`

Copy construct a `basic&lowbar;resolver&lowbar;query` from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-0e7.adoc[basic&lowbar;resolver&lowbar;query](xref:boost/asio/ip/basic_resolver_query.adoc[basic&lowbar;resolver&lowbar;query] const& other);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-0e7.adoc[_» more&period;&period;&period;_]#

Move construct a `basic&lowbar;resolver&lowbar;query` from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-02.adoc[basic&lowbar;resolver&lowbar;query](xref:boost/asio/ip/basic_resolver_query.adoc[basic&lowbar;resolver&lowbar;query]&& other);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-02.adoc[_» more&period;&period;&period;_]#

Construct with specified service name for any protocol&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-0ef.adoc[basic&lowbar;resolver&lowbar;query](
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;query&lowbar;base::flags] resolve&lowbar;flags = passive &verbar; address&lowbar;configured);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-0ef.adoc[_» more&period;&period;&period;_]#

Construct with specified service name for a given protocol&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-0d.adoc[basic&lowbar;resolver&lowbar;query](
    xref:boost/asio/ip/basic_resolver_query/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;query&lowbar;base::flags] resolve&lowbar;flags = passive &verbar; address&lowbar;configured);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-0d.adoc[_» more&period;&period;&period;_]#

Construct with specified host name and service name for any protocol&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-04.adoc[basic&lowbar;resolver&lowbar;query](
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;query&lowbar;base::flags] resolve&lowbar;flags = address&lowbar;configured);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-04.adoc[_» more&period;&period;&period;_]#

Construct with specified host name and service name for a given protocol&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver_query/2constructor-09.adoc[basic&lowbar;resolver&lowbar;query](
    xref:boost/asio/ip/basic_resolver_query/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;query&lowbar;base::flags] resolve&lowbar;flags = address&lowbar;configured);
----

[.small]#xref:boost/asio/ip/basic_resolver_query/2constructor-09.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *service*
| A string identifying the requested service&period; This may be a descriptive name or a numeric string corresponding to a port number&period;
| *resolve&lowbar;flags*
| A set of flags that determine how name resolution should be performed&period; The default flags are suitable for local service binding&period;
| *protocol*
| A protocol object, normally representing either the IPv4 or IPv6 version of an internet protocol&period;
| *host*
| A string identifying a location&period; May be a descriptive name or a numeric address string&period; If an empty string and the passive flag has been specified, the resolved endpoints are suitable for local service binding&period; If an empty string and passive is not specified, the resolved endpoints will use the loopback address&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
