[#boost-asio-ip-make_address_v4-06c]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::make&lowbar;address&lowbar;v4
:relfileprefix: ../../../
:mrdocs:

`make&lowbar;address&lowbar;v4` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;ip&sol;address&lowbar;v4&period;hpp&gt;`

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-08.adoc[make&lowbar;address&lowbar;v4](std::string&lowbar;view str);
----

[.small]#xref:boost/asio/ip/make_address_v4-08.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an unsigned integer in host byte order&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-077.adoc[make&lowbar;address&lowbar;v4](xref:boost/asio/ip/address_v4/uint_type.adoc[address&lowbar;v4::uint&lowbar;type] addr);
----

[.small]#xref:boost/asio/ip/make_address_v4-077.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from raw bytes in network order&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-07a.adoc[make&lowbar;address&lowbar;v4](xref:boost/asio/ip/address_v4/bytes_type.adoc[address&lowbar;v4::bytes&lowbar;type] const& bytes);
----

[.small]#xref:boost/asio/ip/make_address_v4-07a.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-01.adoc[make&lowbar;address&lowbar;v4](std::string const& str);
----

[.small]#xref:boost/asio/ip/make_address_v4-01.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-0d.adoc[make&lowbar;address&lowbar;v4](char const* str);
----

[.small]#xref:boost/asio/ip/make_address_v4-0d.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-05.adoc[make&lowbar;address&lowbar;v4](
    std::string&lowbar;view str,
    boost::system::error&lowbar;code& ec) noexcept;
----

[.small]#xref:boost/asio/ip/make_address_v4-05.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from a IPv4&hyphen;mapped IPv6 address&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-072.adoc[make&lowbar;address&lowbar;v4](
    xref:boost/asio/ip/v4_mapped_t.adoc[v4&lowbar;mapped&lowbar;t],
    xref:boost/asio/ip/address_v6.adoc[address&lowbar;v6] const& v6&lowbar;addr);
----

[.small]#xref:boost/asio/ip/make_address_v4-072.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-00.adoc[make&lowbar;address&lowbar;v4](
    std::string const& str,
    boost::system::error&lowbar;code& ec) noexcept;
----

[.small]#xref:boost/asio/ip/make_address_v4-00.adoc[_» more&period;&period;&period;_]#

Create an IPv4 address from an IP address string in dotted decimal form&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4]
xref:boost/asio/ip/make_address_v4-062.adoc[make&lowbar;address&lowbar;v4](
    char const* str,
    boost::system::error&lowbar;code& ec) noexcept;
----

[.small]#xref:boost/asio/ip/make_address_v4-062.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
