[#boost-asio-ip-operator_eq-0dd]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::operator&equals;&equals;
:relfileprefix: ../../../
:mrdocs:

Equality operators

== Synopses

Declared in `&lt;boost&sol;asio&sol;ip&sol;address&period;hpp&gt;`

Compare two addresses for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-0d3.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4] const& a1,
    xref:boost/asio/ip/address_v4.adoc[address&lowbar;v4] const& a2) noexcept;
----

[.small]#xref:boost/asio/ip/operator_eq-0d3.adoc[_» more&period;&period;&period;_]#

Compare two addresses for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-09.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/basic_address_iterator-07.adoc[basic&lowbar;address&lowbar;iterator&lt;address&lowbar;v6&gt;] const& a,
    xref:boost/asio/ip/basic_address_iterator-07.adoc[basic&lowbar;address&lowbar;iterator&lt;address&lowbar;v6&gt;] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-09.adoc[_» more&period;&period;&period;_]#

Compare two addresses for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-01c.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/address_v6.adoc[address&lowbar;v6] const& a1,
    xref:boost/asio/ip/address_v6.adoc[address&lowbar;v6] const& a2) noexcept;
----

[.small]#xref:boost/asio/ip/operator_eq-01c.adoc[_» more&period;&period;&period;_]#

Compare two addresses for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-0d7.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/address.adoc[address] const& a1,
    xref:boost/asio/ip/address.adoc[address] const& a2) noexcept;
----

[.small]#xref:boost/asio/ip/operator_eq-0d7.adoc[_» more&period;&period;&period;_]#

Compare two addresses for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-0e8.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/basic_address_iterator-00.adoc[basic&lowbar;address&lowbar;iterator&lt;address&lowbar;v4&gt;] const& a,
    xref:boost/asio/ip/basic_address_iterator-00.adoc[basic&lowbar;address&lowbar;iterator&lt;address&lowbar;v4&gt;] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-0e8.adoc[_» more&period;&period;&period;_]#

Compare two networks for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-0c.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/network_v4.adoc[network&lowbar;v4] const& a,
    xref:boost/asio/ip/network_v4.adoc[network&lowbar;v4] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-0c.adoc[_» more&period;&period;&period;_]#

Compare two networks for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-02.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/network_v6.adoc[network&lowbar;v6] const& a,
    xref:boost/asio/ip/network_v6.adoc[network&lowbar;v6] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-02.adoc[_» more&period;&period;&period;_]#

Compare two endpoints for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-06.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/basic_endpoint.adoc[basic&lowbar;endpoint&lt;InternetProtocol&gt;] const& e1,
    xref:boost/asio/ip/basic_endpoint.adoc[basic&lowbar;endpoint&lt;InternetProtocol&gt;] const& e2) noexcept;
----

[.small]#xref:boost/asio/ip/operator_eq-06.adoc[_» more&period;&period;&period;_]#

Test two iterators for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-00.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/basic_resolver_iterator.adoc[basic&lowbar;resolver&lowbar;iterator] const& a,
    xref:boost/asio/ip/basic_resolver_iterator.adoc[basic&lowbar;resolver&lowbar;iterator] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-00.adoc[_» more&period;&period;&period;_]#

Test two iterators for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-016.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/basic_resolver_results.adoc[basic&lowbar;resolver&lowbar;results] const& a,
    xref:boost/asio/ip/basic_resolver_results.adoc[basic&lowbar;resolver&lowbar;results] const& b);
----

[.small]#xref:boost/asio/ip/operator_eq-016.adoc[_» more&period;&period;&period;_]#

Compare two protocols for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-08.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/icmp.adoc[icmp] const& p1,
    xref:boost/asio/ip/icmp.adoc[icmp] const& p2);
----

[.small]#xref:boost/asio/ip/operator_eq-08.adoc[_» more&period;&period;&period;_]#

Compare two protocols for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-012.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/tcp.adoc[tcp] const& p1,
    xref:boost/asio/ip/tcp.adoc[tcp] const& p2);
----

[.small]#xref:boost/asio/ip/operator_eq-012.adoc[_» more&period;&period;&period;_]#

Compare two protocols for equality&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
bool
xref:boost/asio/ip/operator_eq-0eb.adoc[operator&equals;&equals;](
    xref:boost/asio/ip/udp.adoc[udp] const& p1,
    xref:boost/asio/ip/udp.adoc[udp] const& p2);
----

[.small]#xref:boost/asio/ip/operator_eq-0eb.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
