[#boost-asio-executor-2constructor-0a]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/executor.adoc[executor]::executor
:relfileprefix: ../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;executor&period;hpp&gt;`

Default constructor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-0c.adoc[executor]() noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-0c.adoc[_» more&period;&period;&period;_]#

Copy constructor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-04.adoc[executor](xref:boost/asio/executor.adoc[executor] const& other) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-04.adoc[_» more&period;&period;&period;_]#

Move constructor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-0b.adoc[executor](xref:boost/asio/executor.adoc[executor]&& other) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-0b.adoc[_» more&period;&period;&period;_]#

Construct from nullptr&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-0e.adoc[executor](std::nullptr&lowbar;t value) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-0e.adoc[_» more&period;&period;&period;_]#

Construct a polymorphic wrapper for the specified executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor&gt;
xref:boost/asio/executor/2constructor-05.adoc[executor](Executor e);
----

[.small]#xref:boost/asio/executor/2constructor-05.adoc[_» more&period;&period;&period;_]#

Construct a polymorphic executor that points to the same target as another polymorphic executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-07.adoc[executor](
    std::nothrow&lowbar;t,
    xref:boost/asio/executor.adoc[executor] const& other) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-07.adoc[_» more&period;&period;&period;_]#

Construct a polymorphic executor that moves the target from another polymorphic executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/executor/2constructor-01.adoc[executor](
    std::nothrow&lowbar;t,
    xref:boost/asio/executor.adoc[executor]&& other) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-01.adoc[_» more&period;&period;&period;_]#

Construct a polymorphic wrapper for the specified executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename Executor&gt;
xref:boost/asio/executor/2constructor-06.adoc[executor](
    std::nothrow&lowbar;t,
    Executor e) noexcept;
----

[.small]#xref:boost/asio/executor/2constructor-06.adoc[_» more&period;&period;&period;_]#

Allocator&hyphen;aware constructor to create a polymorphic wrapper for the specified executor&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Executor,
    typename Allocator&gt;
xref:boost/asio/executor/2constructor-0f.adoc[executor](
    std::allocator&lowbar;arg&lowbar;t,
    Allocator const& a,
    Executor e);
----

[.small]#xref:boost/asio/executor/2constructor-0f.adoc[_» more&period;&period;&period;_]#


[.small]#Created with https://www.mrdocs.com[MrDocs]#
