[#boost-asio-basic_waitable_timer-cancel_one]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_waitable_timer.adoc[basic&lowbar;waitable&lowbar;timer]::cancel&lowbar;one
:relfileprefix: ../../../
:mrdocs:

Cancels one asynchronous operation that is waiting on the timer&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;waitable&lowbar;timer&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
size&lowbar;t
cancel&lowbar;one();
----

== Description

This function forces the completion of one pending asynchronous wait operation against the timer&period; Handlers are cancelled in FIFO order&period; The handler for the cancelled operation will be invoked with the boost&colon;&colon;asio&colon;&colon;error&colon;&colon;operation&lowbar;aborted error code&period;

Cancelling the timer does not change the expiry time&period;

[NOTE]
If the timer has already expired when cancel&lowbar;one() is called, then the handlers for asynchronous wait operations will&colon;

* have already been invoked&semi; or
* have been queued for invocation in the near future&period;

These handlers can no longer be cancelled, and therefore are passed an error code that indicates the successful completion of the wait operation&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of asynchronous operations that were cancelled&period; That is, either 0 or 1&period;


[.small]#Created with https://www.mrdocs.com[MrDocs]#
