[#boost-asio-basic_seq_packet_socket-2constructor-06]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]::basic&lowbar;seq&lowbar;packet&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket without opening it&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;seq&lowbar;packet&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
basic&lowbar;seq&lowbar;packet&lowbar;socket(
    ExecutionContext& context,
    int = 0);
----

== Description

This constructor creates a sequenced packet socket without opening it&period; The socket needs to be opened and then connected or accepted before data can be sent or received on it&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *context*
| An execution context which provides the I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
