[#boost-asio-basic_seq_packet_socket-2constructor-03]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]::basic&lowbar;seq&lowbar;packet&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket, opening it and binding it to the given local endpoint&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;seq&lowbar;packet&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;seq&lowbar;packet&lowbar;socket(
    xref:boost/asio/basic_seq_packet_socket/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_seq_packet_socket/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint);
----

== Description

This constructor creates a sequenced packet socket and automatically opens it bound to the specified endpoint on the local machine&period; The protocol used is the protocol associated with the given endpoint&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *ex*
| The I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
| *endpoint*
| An endpoint on the local machine to which the sequenced packet socket will be bound&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
