[#boost-asio-basic_seq_packet_socket-2constructor-0d]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]::basic&lowbar;seq&lowbar;packet&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Constructors

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;seq&lowbar;packet&lowbar;socket&period;hpp&gt;`

Move&hyphen;construct a basic&lowbar;seq&lowbar;packet&lowbar;socket from another&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_seq_packet_socket/2constructor-0c.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]&& other) noexcept;
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-0c.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
explicit
xref:boost/asio/basic_seq_packet_socket/2constructor-0e.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](xref:boost/asio/basic_seq_packet_socket/executor_type.adoc[executor&lowbar;type] const& ex);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-0e.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket, opening it and binding it to the given local endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_seq_packet_socket/2constructor-03.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    xref:boost/asio/basic_seq_packet_socket/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_seq_packet_socket/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-03.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;seq&lowbar;packet&lowbar;socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_seq_packet_socket/2constructor-00.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    xref:boost/asio/basic_seq_packet_socket/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_seq_packet_socket/protocol_type.adoc[protocol&lowbar;type] const& protocol);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-00.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket without opening it&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_seq_packet_socket/2constructor-06.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    ExecutionContext& context,
    int = 0);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-06.adoc[_» more&period;&period;&period;_]#

Move&hyphen;construct a basic&lowbar;seq&lowbar;packet&lowbar;socket from a socket of another protocol type&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename Protocol1,
    typename Executor1&gt;
xref:boost/asio/basic_seq_packet_socket/2constructor-0915.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket&lt;Protocol1, Executor1&gt;]&& other,
    int = 0);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-0915.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket on an existing native socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/basic_seq_packet_socket/2constructor-019.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    xref:boost/asio/basic_seq_packet_socket/executor_type.adoc[executor&lowbar;type] const& ex,
    xref:boost/asio/basic_seq_packet_socket/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/basic_seq_packet_socket/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;socket);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-019.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket, opening it and binding it to the given local endpoint&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_seq_packet_socket/2constructor-0917.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    ExecutionContext& context,
    xref:boost/asio/basic_seq_packet_socket/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint,
    int = 0);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-0917.adoc[_» more&period;&period;&period;_]#

Construct and open a basic&lowbar;seq&lowbar;packet&lowbar;socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_seq_packet_socket/2constructor-014.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    ExecutionContext& context,
    xref:boost/asio/basic_seq_packet_socket/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-014.adoc[_» more&period;&period;&period;_]#

Construct a basic&lowbar;seq&lowbar;packet&lowbar;socket on an existing native socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
xref:boost/asio/basic_seq_packet_socket/2constructor-0a.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket](
    ExecutionContext& context,
    xref:boost/asio/basic_seq_packet_socket/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    xref:boost/asio/basic_seq_packet_socket/native_handle_type.adoc[native&lowbar;handle&lowbar;type] const& native&lowbar;socket,
    int = 0);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/2constructor-0a.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;seq&lowbar;packet&lowbar;socket object from which the move will occur&period;
| *ex*
| The I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
| *endpoint*
| An endpoint on the local machine to which the sequenced packet socket will be bound&period;
| *protocol*
| An object specifying protocol parameters to be used&period;
| *context*
| An execution context which provides the I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
| *native&lowbar;socket*
| The new underlying socket implementation&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
