[#boost-asio-basic_seq_packet_socket-async_receive-0a]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]::async&lowbar;receive
:relfileprefix: ../../../
:mrdocs:

Start an asynchronous receive&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;seq&lowbar;packet&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename MutableBufferSequence,
    typename ReadToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(async&lowbar;initiate&lt;ReadToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, std&colon;&colon;size&lowbar;t)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;receive&lowbar;with&lowbar;flags&gt;(), token,
          buffers, socket&lowbar;base&colon;&colon;message&lowbar;flags(0), &amp;out&lowbar;flags))
async&lowbar;receive(
    MutableBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags]& out&lowbar;flags,
    ReadToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

== Description

This function is used to asynchronously receive data from the sequenced packet socket&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error, // Result of operation.
  std::size_t bytes_transferred // Number of bytes received.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, std::size_t) 
----
== Example
To receive into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
socket.async_receive(boost::asio::buffer(data, size), out_flags, handler);
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on receiving into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

== Per&hyphen;Operation Cancellation
On POSIX or Windows operating systems, this asynchronous operation supports cancellation for the following boost&colon;&colon;asio&colon;&colon;cancellation&lowbar;type values&colon;

* `cancellation&lowbar;type&colon;&colon;terminal`
* `cancellation&lowbar;type&colon;&colon;partial`
* `cancellation&lowbar;type&colon;&colon;total`

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period; Although the buffers object may be copied as necessary, ownership of the underlying memory blocks is retained by the caller, which must guarantee that they remain valid until the completion handler is called&period;
| *out&lowbar;flags*
| Once the asynchronous operation completes, contains flags associated with the received data&period; For example, if the socket&lowbar;base&colon;&colon;message&lowbar;end&lowbar;of&lowbar;record bit is set then the received data marks the end of a record&period; The caller must guarantee that the referenced variable remains valid until the completion handler is called&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the receive completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
