[#boost-asio-basic_seq_packet_socket-receive-04]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_seq_packet_socket.adoc[basic&lowbar;seq&lowbar;packet&lowbar;socket]::receive
:relfileprefix: ../../../
:mrdocs:

`receive` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;seq&lowbar;packet&lowbar;socket&period;hpp&gt;`

Receive some data on the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_seq_packet_socket/receive-0b.adoc[receive](
    MutableBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags]& out&lowbar;flags);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/receive-0b.adoc[_» more&period;&period;&period;_]#

Receive some data on the socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_seq_packet_socket/receive-0d3.adoc[receive](
    MutableBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] in&lowbar;flags,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags]& out&lowbar;flags);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/receive-0d3.adoc[_» more&period;&period;&period;_]#

Receive some data on a connected socket&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
xref:boost/asio/basic_seq_packet_socket/receive-0d4.adoc[receive](
    MutableBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] in&lowbar;flags,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags]& out&lowbar;flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/basic_seq_packet_socket/receive-0d4.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period; An error code of boost&colon;&colon;asio&colon;&colon;error&colon;&colon;eof indicates that the connection was closed by the peer&period;
|===

== Return Value

* The number of bytes received&period;
* The number of bytes received&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period;
| *out&lowbar;flags*
| After the receive call completes, contains flags associated with the received data&period; For example, if the socket&lowbar;base&colon;&colon;message&lowbar;end&lowbar;of&lowbar;record bit is set then the received data marks the end of a record&period;
| *in&lowbar;flags*
| Flags specifying how the receive call is to be made&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
