[#boost-asio-ip-basic_resolver-async_resolve-0c3]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::xref:boost/asio/ip/basic_resolver.adoc[basic&lowbar;resolver]::async&lowbar;resolve
:relfileprefix: ../../../../
:mrdocs:

Asynchronously perform forward resolution of a query to a list of entries&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;ip&sol;basic&lowbar;resolver&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token,
          declval&lt;basic&lowbar;resolver&lowbar;query&lt;protocol&lowbar;type&gt;&amp;&gt;()))
async&lowbar;resolve(
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

== Description

This function is used to resolve host and service names into a list of endpoint entries&period; It is an initiating function for an `asynchronous&lowbar;operation`, and always returns immediately&period;

[,cpp]
----
void handler(
  const boost::system::error_code& error, // Result of operation.
  resolver::results_type results // Resolved endpoints as a range.
); 
----
Regardless of whether the asynchronous operation completes immediately or not, the completion handler will not be invoked from within this function&period; On immediate completion, invocation of the handler will be performed in a manner equivalent to using boost&colon;&colon;asio&colon;&colon;async&lowbar;immediate()&period;

A successful resolve operation is guaranteed to pass a non&hyphen;empty range to the handler&period;

== Completion Signature
[,cpp]
----
void(boost::system::error_code, results_type) 
----
[NOTE]
On POSIX systems, host names may be locally defined in the file &period; On Windows, host names may be defined in the file &period; Remote host name resolution is performed using DNS&period; Operating systems may use additional locations when resolving host names (such as NETBIOS names on Windows)&period;

On POSIX systems, service names are typically defined in the file &period; On Windows, service names may be found in the file &period; Operating systems may use additional locations when resolving service names&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *protocol*
| A protocol object, normally representing either the IPv4 or IPv6 version of an internet protocol&period;
| *host*
| A string identifying a location&period; May be a descriptive name or a numeric address string&period; If an empty string and the passive flag has been specified, the resolved endpoints are suitable for local service binding&period; If an empty string and passive is not specified, the resolved endpoints will use the loopback address&period;
| *service*
| A string identifying the requested service&period; This may be a descriptive name or a numeric string corresponding to a port number&period; May be an empty string, in which case all resolved endpoints will have a port number of 0&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the resolve completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
