[#boost-asio-ip-basic_resolver-async_resolve-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::xref:boost/asio/ip/basic_resolver.adoc[basic&lowbar;resolver]::async&lowbar;resolve
:relfileprefix: ../../../../
:mrdocs:

`async&lowbar;resolve` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;ip&sol;basic&lowbar;resolver&period;hpp&gt;`

Asynchronously perform reverse resolution of an endpoint to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token, e))
xref:boost/asio/ip/basic_resolver/async_resolve-0c2.adoc[async&lowbar;resolve](
    xref:boost/asio/ip/basic_resolver/endpoint_type.adoc[endpoint&lowbar;type] const& e,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/ip/basic_resolver/async_resolve-0c2.adoc[_» more&period;&period;&period;_]#

Asynchronously perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token,
          declval&lt;basic&lowbar;resolver&lowbar;query&lt;protocol&lowbar;type&gt;&amp;&gt;()))
xref:boost/asio/ip/basic_resolver/async_resolve-032.adoc[async&lowbar;resolve](
    std::string const& host,
    std::string const& service,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/ip/basic_resolver/async_resolve-032.adoc[_» more&period;&period;&period;_]#

Asynchronously perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token,
          declval&lt;basic&lowbar;resolver&lowbar;query&lt;protocol&lowbar;type&gt;&amp;&gt;()))
xref:boost/asio/ip/basic_resolver/async_resolve-0c3.adoc[async&lowbar;resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/ip/basic_resolver/async_resolve-0c3.adoc[_» more&period;&period;&period;_]#

Asynchronously perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token,
          declval&lt;basic&lowbar;resolver&lowbar;query&lt;protocol&lowbar;type&gt;&amp;&gt;()))
xref:boost/asio/ip/basic_resolver/async_resolve-07.adoc[async&lowbar;resolve](
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/ip/basic_resolver/async_resolve-07.adoc[_» more&period;&period;&period;_]#

Asynchronously perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ResolveToken = xref:boost/asio/default_completion_token_t.adoc[default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;]&gt;
decltype(boost&colon;&colon;asio&colon;&colon;async&lowbar;initiate&lt;ResolveToken,
        void (boost&colon;&colon;system&colon;&colon;error&lowbar;code, results&lowbar;type)&gt;(
          declval&lt;initiate&lowbar;async&lowbar;resolve&gt;(), token,
          declval&lt;basic&lowbar;resolver&lowbar;query&lt;protocol&lowbar;type&gt;&amp;&gt;()))
xref:boost/asio/ip/basic_resolver/async_resolve-036.adoc[async&lowbar;resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags,
    ResolveToken&& token = default&lowbar;completion&lowbar;token&lowbar;t&lt;executor&lowbar;type&gt;());
----

[.small]#xref:boost/asio/ip/basic_resolver/async_resolve-036.adoc[_» more&period;&period;&period;_]#

== Parameters

[cols=2]
|===
| Name
| Description
| *e*
| An endpoint object that determines what endpoints will be returned&period;
| *token*
| The `completion&lowbar;token` that will be used to produce a completion handler, which will be called when the resolve completes&period; Potential completion tokens include xref:boost/asio/use_future.adoc[`use&lowbar;future`], `use&lowbar;awaitable`, `yield&lowbar;context`, or a function object with the correct completion signature&period; The function signature of the completion handler must be&colon;
| *host*
| A string identifying a location&period; May be a descriptive name or a numeric address string&period; If an empty string and the passive flag has been specified, the resolved endpoints are suitable for local service binding&period; If an empty string and passive is not specified, the resolved endpoints will use the loopback address&period;
| *service*
| A string identifying the requested service&period; This may be a descriptive name or a numeric string corresponding to a port number&period; May be an empty string, in which case all resolved endpoints will have a port number of 0&period;
| *protocol*
| A protocol object, normally representing either the IPv4 or IPv6 version of an internet protocol&period;
| *resolve&lowbar;flags*
| A set of flags that determine how name resolution should be performed&period; The default flags are suitable for communication with remote hosts&period; See the xref:boost/asio/ip/resolver_base.adoc[`resolver&lowbar;base`] documentation for the set of available flags&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
