[#boost-asio-ip-basic_resolver-resolve-00]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::xref:boost/asio/ip/basic_resolver.adoc[basic&lowbar;resolver]::resolve
:relfileprefix: ../../../../
:mrdocs:

`resolve` overloads

== Synopses

Declared in `&lt;boost&sol;asio&sol;ip&sol;basic&lowbar;resolver&period;hpp&gt;`

Perform reverse resolution of an endpoint to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0aa.adoc[resolve](xref:boost/asio/ip/basic_resolver/endpoint_type.adoc[endpoint&lowbar;type] const& e);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0aa.adoc[_» more&period;&period;&period;_]#

Perform reverse resolution of an endpoint to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-03.adoc[resolve](
    xref:boost/asio/ip/basic_resolver/endpoint_type.adoc[endpoint&lowbar;type] const& e,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-03.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-05.adoc[resolve](
    std::string const& host,
    std::string const& service);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-05.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0d8.adoc[resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0d8.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0a7.adoc[resolve](
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0a7.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-09.adoc[resolve](
    std::string const& host,
    std::string const& service,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-09.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0c.adoc[resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0c.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0f.adoc[resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0f.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-0d4.adoc[resolve](
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-0d4.adoc[_» more&period;&period;&period;_]#

Perform forward resolution of a query to a list of entries&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
xref:boost/asio/ip/basic_resolver/resolve-02.adoc[resolve](
    xref:boost/asio/ip/basic_resolver/protocol_type.adoc[protocol&lowbar;type] const& protocol,
    std::string const& host,
    std::string const& service,
    xref:boost/asio/ip/resolver_base/flags.adoc[resolver&lowbar;base::flags] resolve&lowbar;flags,
    boost::system::error&lowbar;code& ec);
----

[.small]#xref:boost/asio/ip/basic_resolver/resolve-02.adoc[_» more&period;&period;&period;_]#

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

* A range object representing the list of endpoint entries&period; A successful call to this function is guaranteed to return a non&hyphen;empty range&period;
* A range object representing the list of endpoint entries&period; An empty range is returned if an error occurs&period; A successful call to this function is guaranteed to return a non&hyphen;empty range&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *e*
| An endpoint object that determines what endpoints will be returned&period;
| *ec*
| Set to indicate what error occurred, if any&period;
| *host*
| A string identifying a location&period; May be a descriptive name or a numeric address string&period; If an empty string and the passive flag has been specified, the resolved endpoints are suitable for local service binding&period; If an empty string and passive is not specified, the resolved endpoints will use the loopback address&period;
| *service*
| A string identifying the requested service&period; This may be a descriptive name or a numeric string corresponding to a port number&period; May be an empty string, in which case all resolved endpoints will have a port number of 0&period;
| *protocol*
| A protocol object, normally representing either the IPv4 or IPv6 version of an internet protocol&period;
| *resolve&lowbar;flags*
| A set of flags that determine how name resolution should be performed&period; The default flags are suitable for communication with remote hosts&period; See the xref:boost/asio/ip/resolver_base.adoc[`resolver&lowbar;base`] documentation for the set of available flags&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
