[#boost-asio-ip-basic_resolver-resolve-03]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/ip.adoc[ip]::xref:boost/asio/ip/basic_resolver.adoc[basic&lowbar;resolver]::resolve
:relfileprefix: ../../../../
:mrdocs:

Perform reverse resolution of an endpoint to a list of entries&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;ip&sol;basic&lowbar;resolver&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/ip/basic_resolver/results_type.adoc[results&lowbar;type]
resolve(
    xref:boost/asio/ip/basic_resolver/endpoint_type.adoc[endpoint&lowbar;type] const& e,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to resolve an endpoint into a list of endpoint entries&period;

== Return Value

A range object representing the list of endpoint entries&period; An empty range is returned if an error occurs&period; A successful call to this function is guaranteed to return a non&hyphen;empty range&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *e*
| An endpoint object that determines what endpoints will be returned&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
