[#boost-asio-windows-basic_stream_handle-2constructor-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/windows.adoc[windows]::xref:boost/asio/windows/basic_stream_handle.adoc[basic&lowbar;stream&lowbar;handle]::basic&lowbar;stream&lowbar;handle
:relfileprefix: ../../../../
:mrdocs:

Construct a stream handle without opening it&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;windows&sol;basic&lowbar;stream&lowbar;handle&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
basic&lowbar;stream&lowbar;handle(
    ExecutionContext& context,
    xref:boost/asio/defaulted_constraint.adoc[defaulted&lowbar;constraint] = defaulted&lowbar;constraint());
----

== Description

This constructor creates a stream handle without opening it&period; The handle needs to be opened or assigned before data can be written to or read from it&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *context*
| An execution context which provides the I&sol;O executor that the stream handle will use, by default, to dispatch handlers for any asynchronous operations performed on the stream handle&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
