[#boost-asio-windows-basic_stream_handle-operator_assign-06]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/windows.adoc[windows]::xref:boost/asio/windows/basic_stream_handle.adoc[basic&lowbar;stream&lowbar;handle]::operator&equals;
:relfileprefix: ../../../../
:mrdocs:

Move&hyphen;assign a stream handle from another&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;windows&sol;basic&lowbar;stream&lowbar;handle&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
xref:boost/asio/windows/basic_stream_handle.adoc[basic&lowbar;stream&lowbar;handle]&
operator&equals;(xref:boost/asio/windows/basic_stream_handle.adoc[basic&lowbar;stream&lowbar;handle]&& other);
----

== Description

This assignment operator moves a stream handle from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;stream&lowbar;handle(const` executor&lowbar;type&amp;) constructor&period;

== Return Value

Reference to the current object

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other stream handle object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
