[#boost-asio-basic_datagram_socket-2constructor-037]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::basic&lowbar;datagram&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;datagram&lowbar;socket without opening it&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
basic&lowbar;datagram&lowbar;socket(
    ExecutionContext& context,
    int = 0);
----

== Description

This constructor creates a datagram socket without opening it&period; The open() function must be called before data can be sent or received on the socket&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *context*
| An execution context which provides the I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
