[#boost-asio-basic_datagram_socket-2constructor-035]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::basic&lowbar;datagram&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Construct a basic&lowbar;datagram&lowbar;socket, opening it and binding it to the given local endpoint&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ExecutionContext&gt;
basic&lowbar;datagram&lowbar;socket(
    ExecutionContext& context,
    xref:boost/asio/basic_datagram_socket/endpoint_type.adoc[endpoint&lowbar;type] const& endpoint,
    int = 0);
----

== Description

This constructor creates a datagram socket and automatically opens it bound to the specified endpoint on the local machine&period; The protocol used is the protocol associated with the given endpoint&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Parameters

[cols=2]
|===
| Name
| Description
| *context*
| An execution context which provides the I&sol;O executor that the socket will use, by default, to dispatch handlers for any asynchronous operations performed on the socket&period;
| *endpoint*
| An endpoint on the local machine to which the datagram socket will be bound&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
