[#boost-asio-basic_datagram_socket-2constructor-03b]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::basic&lowbar;datagram&lowbar;socket
:relfileprefix: ../../../
:mrdocs:

Move&hyphen;construct a basic&lowbar;datagram&lowbar;socket from another&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
basic&lowbar;datagram&lowbar;socket(xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]&& other) noexcept;
----

== Description

This constructor moves a datagram socket from one object to another&period;

[NOTE]
Following the move, the moved&hyphen;from object is in the same state as if constructed using the `basic&lowbar;datagram&lowbar;socket(const` executor&lowbar;type&amp;) constructor&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *other*
| The other basic&lowbar;datagram&lowbar;socket object from which the move will occur&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
