[#boost-asio-basic_datagram_socket-receive_from-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::receive&lowbar;from
:relfileprefix: ../../../
:mrdocs:

Receive a datagram with the endpoint of the sender&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
receive&lowbar;from(
    MutableBufferSequence const& buffers,
    xref:boost/asio/basic_datagram_socket/endpoint_type.adoc[endpoint&lowbar;type]& sender&lowbar;endpoint);
----

== Description

This function is used to receive a datagram&period; The function call will block until data has been received successfully or an error occurs&period;

== Example
To receive into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
boost::asio::ip::udp::endpoint sender_endpoint;
socket.receive_from(
    boost::asio::buffer(data, size), sender_endpoint);
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on receiving into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes received&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period;
| *sender&lowbar;endpoint*
| An endpoint object that receives the endpoint of the remote sender of the datagram&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
