[#boost-asio-basic_datagram_socket-receive-05]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::receive
:relfileprefix: ../../../
:mrdocs:

Receive some data on a connected socket&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
receive(
    MutableBufferSequence const& buffers,
    xref:boost/asio/socket_base/message_flags.adoc[socket&lowbar;base::message&lowbar;flags] flags,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to receive data on the datagram socket&period; The function call will block until data has been received successfully or an error occurs&period;

[NOTE]
The receive operation can only be used with a connected socket&period; Use the receive&lowbar;from function to receive data on an unconnected datagram socket&period;

== Return Value

The number of bytes received&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period;
| *flags*
| Flags specifying how the receive call is to be made&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
