[#boost-asio-basic_datagram_socket-receive-0d]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_datagram_socket.adoc[basic&lowbar;datagram&lowbar;socket]::receive
:relfileprefix: ../../../
:mrdocs:

Receive some data on a connected socket&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;datagram&lowbar;socket&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename MutableBufferSequence&gt;
size&lowbar;t
receive(MutableBufferSequence const& buffers);
----

== Description

This function is used to receive data on the datagram socket&period; The function call will block until data has been received successfully or an error occurs&period;

[NOTE]
The receive operation can only be used with a connected socket&period; Use the receive&lowbar;from function to receive data on an unconnected datagram socket&period;

== Example
To receive into a single data buffer use the xref:boost/asio/buffer-068.adoc[`buffer`] function as follows&colon;

[,cpp]
----
socket.receive(boost::asio::buffer(data, size)); 
----
See the xref:boost/asio/buffer-068.adoc[`buffer`] documentation for information on receiving into multiple buffers in one go, and how to use it with arrays, boost&colon;&colon;array or std&colon;&colon;vector&period;

== Exceptions

[cols=2]
|===
| Name
| Thrown on
| `boost&colon;&colon;system&colon;&colon;system&lowbar;error`
| Thrown on failure&period;
|===

== Return Value

The number of bytes received&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more buffers into which the data will be received&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
