[#boost-asio-basic_serial_port-write_some-0f]
= xref:boost.adoc[boost]::xref:boost/asio.adoc[asio]::xref:boost/asio/basic_serial_port.adoc[basic&lowbar;serial&lowbar;port]::write&lowbar;some
:relfileprefix: ../../../
:mrdocs:

Write some data to the serial port&period;

== Synopsis

Declared in `&lt;boost&sol;asio&sol;basic&lowbar;serial&lowbar;port&period;hpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename ConstBufferSequence&gt;
size&lowbar;t
write&lowbar;some(
    ConstBufferSequence const& buffers,
    boost::system::error&lowbar;code& ec);
----

== Description

This function is used to write data to the serial port&period; The function call will block until one or more bytes of the data has been written successfully, or until an error occurs&period;

[NOTE]
The write&lowbar;some operation may not transmit all of the data to the peer&period; Consider using the xref:boost/asio/write-02d.adoc[`write`] function if you need to ensure that all data is written before the blocking operation completes&period;

== Return Value

The number of bytes written&period; Returns 0 if an error occurred&period;

== Parameters

[cols=2]
|===
| Name
| Description
| *buffers*
| One or more data buffers to be written to the serial port&period;
| *ec*
| Set to indicate what error occurred, if any&period;
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
